/**
 * The credentialed command families for the `bbx` reference doc: Drive,
 * calendar, Gmail, and the forced wakeup.
 *
 * These verbs work from an agent's shell even though that shell holds no
 * Google credential — the box's server does the credentialed half — so the
 * reference says that once, here, rather than per verb
 * (`docs/plans/agent-capability-delegation.md`). Split out of
 * `bbx-commands.ts` to keep each file under the line limit; assembled there by
 * `generateBbxCommands()`.
 */

/** Hand-written command sections: force-wakeup, drive, calendar, connector. */
export function bbxCommandsConnectors(): string[] {
  return [
    "## Credentialed commands",
    "",
    "The `drive`, `calendar`, and `connector` families need a Google credential,",
    "which your shell deliberately does not hold. They still work: the box's own",
    "server does the credentialed half and hands back the same typed result the",
    "settings page gets. When something is missing, the command says which of three",
    "parties can fix it — you (adjust the command), the boxholder (enable or",
    "authorize), or the machine.",
    "",
    "Every verb that asks Google takes `--json`, which prints exactly one object —",
    "the result, or `{kind, message, fix}` for a refusal — so you never parse prose.",
    "`gws` is the exception: it prints what the upstream command printed.",
    "",
    "## bbx force-wakeup",
    "",
    "Run a wakeup now on the server and report what each connector did.",
    "",
    "```",
    "bbx force-wakeup [--connector <name>] [--json]",
    "```",
    "",
    "`--connector` matches the connector's registered name exactly (`google-drive`,",
    "`google-calendar`, `gmail`). The result says, per connector, what was created,",
    "updated, and pushed — or that it was skipped, and why. Reach for it after",
    "mounting a Drive folder or changing connector configuration, and whenever the",
    "boxholder asks \"did it sync?\"",
    "",
    "## bbx drive",
    "",
    "Mirror and point at Google Drive content. A mount is a card, so everything",
    "here writes cards you can read.",
    "",
    "```bash",
    "bbx drive inspect <url-or-id>        # What is this, and does a card already claim it?",
    "bbx drive mount <url-or-id> <dir>    # Mirror a folder into a directory",
    "bbx drive link <url-or-id> <path>    # Point at any item, copying nothing",
    "bbx drive add <url-or-id> <path>     # Two-way sync one Doc or Sheet",
    "bbx drive unmount <dir-or-card>      # Stop mirroring; children stay put",
    "bbx drive list [folder]              # Browse Drive without writing anything",
    "```",
    "",
    "`inspect` writes nothing — run it before a mount to check the id resolves, and",
    "after one to confirm what landed. A mount reports whether the box's hourly",
    "Drive sync (`check-drive`) is off; if it is, ask the boxholder whether to turn",
    "it on, and use `bbx force-wakeup --connector google-drive` meanwhile.",
    "",
    "`bbx drive sync` runs the connector in your own process, so it works only for",
    "the box's own tooling; `bbx force-wakeup --connector google-drive` is the",
    "equivalent you can run.",
    "",
    "## bbx calendar",
    "",
    "```bash",
    "bbx calendar [timespan]      # Upcoming events: today, 3d, 2w, 1m (default 7d)",
    "bbx calendar calendars       # Every calendar the grant sees, and which sync",
    "bbx calendar add <id>        # Start syncing one",
    "bbx calendar remove <id>     # Stop syncing one",
    "bbx calendar vtimezone       # This box's VTIMEZONE block, for .ics events",
    "```",
    "",
    "Reading events, `add`, and `remove` work off the box's own files. Only",
    "`calendars` asks Google, so only it needs the server.",
    "",
    "## bbx connector gmail",
    "",
    "```bash",
    "bbx connector gmail track <thread-id>   # Materialize one thread as a card",
    "bbx connector gmail pending [rule]      # Untracked rule matches, from local state",
    "bbx connector gmail gws <args...>       # A read-only Google Workspace CLI command",
    "```",
    "",
    "`gws` passes its arguments through to the upstream vocabulary and prints what",
    "that command printed; only read operations are accepted, and anything else is",
    "refused before a token is minted. `pending` reads local state and needs nothing",
    "from Google.",
    "",
    "## bbx wakeup — system-run",
    "",
    "The cycle itself: connectors, jobs, on-wakeup scripts, push. The scheduler and",
    "the server run it, with the credentials it needs; running it yourself syncs",
    "nothing and reports that as \"nothing new\". `bbx force-wakeup` above is how you",
    "trigger a real one.",
    "",
  ];
}
