/**
 * Shared leaf helpers and constants for doc generation.
 *
 * Lives below both `generate-docs.ts` (orchestration) and
 * `generate-docs-compile.ts` (compile/scan helpers) so both can depend on it
 * without forming an import cycle.
 */

export const AGENT_GUIDE_DIR = ".beebox";
export const AGENT_GUIDE_FILE = "agent-guide.md";
/** Box-relative dir for docs compiled from THIS box's content (guides,
 *  personality, box-local card types). Engine docs are not here — see
 *  BOX_PACKAGE_DOCS. */
export const DOCS_DIR = "_content/docs/generated";

/** Name of the engine-docs directory inside the beebox package root. */
export const PACKAGE_DOCS_DIR_NAME = "box-docs";

/**
 * Box-relative path of the engine docs — the reference docs about beebox
 * itself (card types, `bbx` commands, connectors, views, …). They live in the
 * installed package, not the box, so they can never lag the engine that
 * reads them; every pointer an agent sees is built from this constant.
 * Mechanism: `package-docs.ts`.
 */
export const BOX_PACKAGE_DOCS = `node_modules/beebox/${PACKAGE_DOCS_DIR_NAME}`;

/** What every generated guidance file says after its DOCID. */
const GENERATED_NOTICE = "GENERATED by beebox, edits are overwritten";
const DOCID_LINE = /^<!-- DOCID:(.+?); GENERATED by beebox, edits are overwritten -->$/;
/** A leading YAML frontmatter block, through its closing fence's newline. */
const FRONTMATTER = /^---\n[\S\s]*?\n---\n/;

/** Split `content` into its frontmatter block (possibly empty) and the rest. */
function splitFrontmatter(content: string): { head: string; rest: string } {
  const match = FRONTMATTER.exec(content);
  const head = match === null ? "" : match[0];
  return { head, rest: content.slice(head.length) };
}

/**
 * Mark a generated guidance file: `<!-- DOCID:<path>; GENERATED by beebox,
 * edits are overwritten -->`, where `<path>` is the file's box-relative path.
 *
 * The marker is the first line, or the first line after a YAML frontmatter
 * block: Claude Code parses rule `paths:` and skill `name:` frontmatter only
 * when the file opens with it. It does two jobs. A prompt log shows which
 * generated files reached an agent (`grep DOCID:`), and a generator's prune
 * removes only files that carry the marker naming their own path
 * ({@link readDocId}), so a box's hand-written rule or skill survives.
 */
export function withDocId(params: { relativePath: string; content: string }): string {
  const { relativePath, content } = params;
  const { head, rest } = splitFrontmatter(content);
  return `${head}<!-- DOCID:${relativePath}; ${GENERATED_NOTICE} -->\n${rest}`;
}

/** The box-relative path a {@link withDocId} marker names, or null when `content` carries none. */
export function readDocId(content: string): string | null {
  const { rest } = splitFrontmatter(content);
  const firstLine = rest.split("\n", 1)[0] ?? "";
  return DOCID_LINE.exec(firstLine)?.[1] ?? null;
}

/** `content` with its {@link withDocId} marker line removed (unchanged when it has none). */
export function withoutDocId(content: string): string {
  if (readDocId(content) === null) return content;
  const { head, rest } = splitFrontmatter(content);
  return head + rest.slice(rest.indexOf("\n") + 1);
}
