import type { Scenario } from "./chat-scroll-steps";

export const SPACER_SCENARIOS: Scenario[] = [
  {
    name: "finalize-retains-spacer",
    description: "A short reply to a send. Completion must retain the spacer and keep the sent message at the top.",
    steps: [
      { k: "append", px: 300, role: "assistant" },
      { k: "send", px: 40 },
      { k: "append", px: 48, role: "assistant" },
      { k: "stream", chunks: 3, intervalMs: 50, chunkPx: 40 },
      { k: "wait", ms: 500 },
      { k: "finalize", shrinkBy: 20 },
      { k: "wait", ms: 300 },
    ],
    expect: {
      finalUserMessageTopAtMost: 4,
      finalAtBottom: true,
      finalFromBottomAtMost: 4,
      finalHasUnseenContent: false,
    },
  },
  {
    name: "completed-spacer-scrolls-away",
    description: "Scrolling upward consumes only offscreen spacer; returning down cannot recover the removed blank space.",
    steps: [
      { k: "send", px: 40 },
      { k: "append", px: 48, role: "assistant" },
      { k: "wait", ms: 500 },
      { k: "finalize", shrinkBy: 0 },
      { k: "userWheel", deltaY: -100 },
      { k: "wait", ms: 200 },
      { k: "userWheel", deltaY: 100 },
      { k: "wait", ms: 200 },
    ],
    expect: { finalUserMessageTopNear: 99, finalSpareAtMost: 2, writesAtMost: 1 },
  },
  {
    name: "completed-spacer-content-growth",
    description: "Later content consumes retained room without moving the sent message.",
    steps: [
      { k: "send", px: 40 },
      { k: "append", px: 48, role: "assistant" },
      { k: "wait", ms: 500 },
      { k: "finalize", shrinkBy: 0 },
      { k: "append", px: 40, role: "assistant" },
      { k: "wait", ms: 200 },
    ],
    expect: { finalUserMessageTopAtMost: 4, finalSpareAtMost: 2, writesAtMost: 1 },
  },
  {
    name: "completed-spacer-next-send",
    description: "A second send gets fresh anchoring room after the previous spacer was consumed.",
    steps: [
      { k: "send", px: 40 },
      { k: "append", px: 48, role: "assistant" },
      { k: "wait", ms: 500 },
      { k: "finalize", shrinkBy: 0 },
      { k: "userWheel", deltaY: -500 },
      { k: "wait", ms: 200 },
      { k: "send", px: 40 },
      { k: "append", px: 48, role: "assistant" },
      { k: "wait", ms: 500 },
      { k: "finalize", shrinkBy: 0 },
    ],
    expect: { finalUserMessageTopAtMost: 4, finalSpareAtMost: 2, writesAtMost: 2 },
  },

  {
    name: "spacer-survives-tall-reply-viewport-resize",
    description: "Real content below a reduced viewport must not consume the spacer needed when the viewport returns.",
    steps: [
      { k: "send", px: 40 },
      { k: "append", px: 240, role: "assistant" },
      { k: "wait", ms: 500 },
      { k: "chromeResize", px: 300 },
      { k: "wait", ms: 200 },
      { k: "chromeResize", px: 96 },
      { k: "wait", ms: 200 },
    ],
    expect: { finalUserMessageTopAtMost: 4, writesAtMost: 1 },
  },
  {
    name: "spacer-survives-long-to-short-finalize",
    description: "A reply outgrows the viewport then finalizes shorter; real content never consumes its underlying minimum height.",
    steps: [
      { k: "send", px: 40 },
      { k: "append", px: 600, role: "assistant" },
      { k: "wait", ms: 500 },
      { k: "finalize", shrinkBy: 500 },
      { k: "wait", ms: 200 },
    ],
    expect: { finalUserMessageTopAtMost: 4, writesAtMost: 1 },
  },
  {
    name: "spacer-survives-no-response",
    description: "Removing the provisional reply transfers the retained room back to the user message before paint.",
    steps: [
      { k: "send", px: 40 },
      { k: "append", px: 48, role: "assistant" },
      { k: "wait", ms: 500 },
      { k: "changeTail", operation: "remove" },
      { k: "wait", ms: 200 },
    ],
    expect: { finalUserMessageTopAtMost: 4, writesAtMost: 2 },
  },
  {
    name: "spacer-no-response-during-send-ease",
    description: "An immediately suppressed response must not interrupt send anchoring.",
    steps: [
      { k: "send", px: 40 },
      { k: "append", px: 48, role: "assistant" },
      { k: "changeTail", operation: "remove" },
      { k: "wait", ms: 500 },
    ],
    expect: { finalUserMessageTopAtMost: 4 },
  },
  {
    name: "spacer-no-response-rekeys-user",
    description: "Authoritative history replaces the pending user's key while removing the reply in the same commit.",
    steps: [
      { k: "send", px: 40 },
      { k: "append", px: 48, role: "assistant" },
      { k: "wait", ms: 500 },
      { k: "changeTail", operation: "remove-and-rekey" },
      { k: "wait", ms: 200 },
    ],
    expect: { finalUserMessageTopAtMost: 4, writesAtMost: 2 },
  },
  {
    name: "spacer-finalize-reorders-pending-bubble",
    description: "A tall pending bubble moves from before the streaming reply to after the short final reply.",
    steps: [
      { k: "send", px: 40 },
      { k: "append", px: 160, role: "assistant" },
      { k: "append", px: 48, role: "assistant" },
      { k: "wait", ms: 500 },
      { k: "changeTail", operation: "swap" },
      { k: "wait", ms: 200 },
    ],
    expect: { finalUserMessageTopAtMost: 4, writesAtMost: 2 },
  },
  {
    name: "removed-long-reply-does-not-leave-blank-viewport",
    description: "If the reply being read disappears, return to remaining content instead of preserving an empty viewport.",
    steps: [
      { k: "send", px: 40 },
      { k: "append", px: 900, role: "assistant" },
      { k: "wait", ms: 500 },
      { k: "button", behavior: "instant" },
      { k: "changeTail", operation: "remove" },
      { k: "wait", ms: 200 },
    ],
    expect: { finalUserMessageTopAtMost: 4 },
  },
];
