/**
 * Scheduling/automation + chat command sections for the `bbx` command
 * reference doc. Split out of generate-docs-bbx-commands.ts to keep each
 * file under the line limit; assembled there by generateBbxCommands().
 */

import { BOX_PACKAGE_DOCS } from "../shared.js";

/**
 * Hand-written command sections: procedure, tick, scheduled, run-summary, health, scheduler,
 * finalize, chat.
 */
export function bbxCommandsScheduling(): string[] {
  return [
    "## bbx procedure",
    "",
    `Run and manage declarative procedures. See \`${BOX_PACKAGE_DOCS}/procedures.md\` for details.`,
    "",
    "```bash",
    "bbx procedure run <name-or-path>          # Run a procedure",
    "bbx procedure run <name> --step <id>      # Run a single step",
    "bbx procedure run <name> --dry-run        # Preview without executing",
    'bbx procedure run <name> --directive "text" # Pass a directive to agents',
    "bbx procedure list                        # List available procedures",
    "bbx procedure status [run-dir]            # Show status of latest/specific run",
    "```",
    "",
    "The `<name-or-path>` argument can be a bare name (resolves to `_config/procedures/<name>.procedure.card`)",
    "or a direct path to any `.procedure.card` file.",
    "",
    "The `--directive` flag passes an opaque string that appears as `<directive>...</directive>` in every agent's",
    "system prompt within the procedure. Use it to customize behavior without modifying the procedure card.",
    "",
    "## bbx tick",
    "",
    "Evaluate scheduled scripts and run any that are due.",
    "",
    "```",
    "bbx tick [--dry-run] [--script <name>] [--force] [--box <path>]",
    "```",
    "",
    "Checks all `_config/schedules/*.scheduled-script.card` files against their cron/at/rrule schedules.",
    "Runs due scripts, updates last-run timestamps, and deletes one-shot (`once`) scripts after execution.",
    "",
    "**Options:**",
    "- `--dry-run` — Show which scripts would run without executing them",
    "- `--script <name>` — Only evaluate a specific script (by filename stem)",
    "- `--force` — Run the `--script` now, bypassing schedule, budget, and active-chat checks. Use this when the boxholder asks for a run from chat — a plain tick defers on the chat session itself. Running scripts/procedures and live lock-group holders still defer; force never preempts running work.",
    "- `--box <path>` — Target a specific box instead of the current directory",
    "",
    "Note: scripts with `on-wakeup=\"true\"` also run during `bbx engine wakeup`, subject to their `not-before` interval.",
    "",
    "## bbx scheduled",
    "",
    "List all scheduled scripts and their status.",
    "",
    "```",
    "bbx scheduled",
    "```",
    "",
    "Shows each schedule's name, type (cron/at/rrule), next due time, last run, and flags (on-wakeup, once, enabled).",
    "",
    "## bbx run-summary",
    "",
    "End a scheduled run with a summary the boxholder sees in the dashboard's run history.",
    "",
    "```bash",
    'bbx run-summary "Filed 3 receipts" --body "- 2 from email\\n- 1 skipped: no amount"',
    'bbx run-summary "2 imports failed" --priority attention --notes - < details.md',
    "```",
    "",
    "Headline up to 120 characters; `--body` (1 KB) and `--notes` (4 KB, shown collapsed) are Markdown, and `-` reads",
    "stdin. `--priority attention` marks a run worth a look; the default is `normal`. It writes to `$BBX_SUMMARY_FILE`,",
    "set by the scheduler; outside a scheduled run it prints the summary instead. The last call in a run wins.",
    "",
    "## bbx health",
    "",
    "Show scheduled-task health: failing, overdue, blocked, inconclusive, or",
    "invalid tasks, plus whether the scheduler daemon is alive.",
    "",
    "```",
    "bbx health [--json] [--all] [--box <path>]",
    "```",
    "",
    "Per task: status, last attempt vs last success (they diverge while failing),",
    "consecutive-failure count, and the last error. `--all` includes disabled tasks.",
    "Exit code 1 when anything is failing/overdue/invalid or the scheduler heartbeat",
    "is stale, so scripts can gate on it. Deliberate skips (budget exhausted, missing",
    "connector, disabled) show as blocked/disabled, never as failures. A task whose",
    "last run completed its work but whose check reached no verdict shows as `?`",
    "inconclusive — unknown, not broken — and does not affect the exit code.",
    "`inconclusive` means the last run did its work but its check never reached a",
    "verdict — unknown, not broken; do not redo the work on that basis.",
    "",
    "## bbx scheduler",
    "",
    "Read the state of the background scheduler daemon that runs `bbx tick` on a",
    "recurring basis. Starting and installing the daemon is an operator act and",
    "lives under `bbx engine scheduler`.",
    "",
    "```",
    "bbx scheduler status                        # Show boxes + launchd status",
    "bbx scheduler log [--box <path>] [--limit <n>] [--errors] [--json]",
    "```",
    "",
    "The daemon polls every 60 seconds (configurable). Config at `~/.config/beebox/scheduler.json`.",
    "Per-box logs are written to `.beebox/scheduler.jsonl` (JSONL, auto-rotated at 1MB).",
    "Each log entry records which scripts ran/skipped/errored with timestamps and durations.",
    "Agents can read `.beebox/scheduler.jsonl` to understand recent scheduling activity.",
    "",
    "## bbx finalize",
    "",
    "Run outbound connectors to flush pending output cards.",
    "",
    "```",
    "bbx finalize [-c, --connector <name>]",
    "```",
    "",
    "Symmetric counterpart to `bbx engine wakeup`. Sends any pending cards in `_bookkeeping/output/`",
    "(e.g. telegram messages). Called automatically by the reactor after job processing,",
    "or run manually to flush output.",
    "",
    ...bbxCommandsNotify(),
    ...bbxCommandsChat(),
  ];
}

/** The `## bbx notify` section: reaching the boxholder now, moved from the agent guide. */
function bbxCommandsNotify(): string[] {
  return [
    "## bbx notify",
    "",
    "Send the boxholder a notification now. Run `bbx notify --check` first when you are about to",
    "promise a reminder or a watch: it prints which channels can reach the person and exits 1 when",
    "none can.",
    "",
    "`--loudness` is `dot` (badge only), `quiet` (muted; held back while they are in the app), or",
    "`loud` (sound). `--target` is where a tap lands: `chat:<sessionId>`, `chat:new`, `card:<path>`,",
    "`question:<path>`, `admin:<section>`, `dashboard`. `--tag <key>` makes a later notification",
    "replace this one. A long body goes on stdin with `--body -`; without it stdin is never read.",
    "`--dry-run` prints what a send would do without sending. A failure the person must fix, after",
    "they left the chat it came from:",
    "",
    "```sh",
    "bbx notify \"I couldn't read the receipt you photographed\" --loudness quiet \\",
    "  --target chat:<that sessionId> --body \"The total is cut off. Can you retake it?\"",
    "```",
    "",
    "In a chat turn, `<callout loudness=\"quiet\">` does this for the turn's outcome. A reminder at a",
    "time is a scheduled-script card with `notify:`; a watch that notifies when something happens is",
    "a scheduled-script card whose `runs:` pipes `bbx changes` into `bbx judge` and then an agent or",
    "`bbx notify`. Both examples are in `card-scheduled-script.md`; the judgment card is",
    "`card-judgment.md`.",
    "",
  ];
}

/** The `## bbx chat` section: self-note + the voice-recording commands. */
function bbxCommandsChat(): string[] {
  return [
    "## bbx chat",
    "",
    "Talk to the live chat session.",
    "",
    "- `bbx chat self-note \"<body>\" [--ref <path>] [--commit <hash>]` — Post an",
    "  agent-authored record into the chat transcript without triggering a reply.",
    "- `bbx chat screenshot [--session <id>] [--timeout <seconds>]` — Ask the",
    "  user's connected chat tab for a screenshot of what they currently see in",
    "  the box UI, and print the saved image path (Read it) plus a `fidelity:`",
    "  line. Reach for it on visual/layout questions — how a card or custom view",
    "  actually renders — where `whats-changed` (content) and reading the source",
    "  can't help. It asks the user's browser, so instead of a path it may print",
    "  one of `declined:` / `no-client:` / `timeout:` / `failed:` / `error:`",
    "  telling you it was declined or unavailable. Defaults: the session from",
    "  `BBX_CHAT_SESSION_ID`, a 45s wait.",
    "- `bbx chat ask-about-audio \"<question>\" --message <id> [--context <text>]`",
    "  — Ask an audio-capable model (Gemini) a question about a specific voice",
    "  message (or `--file <path>` for any audio file). `--message` is",
    "  required unless `--file` is given: read the `message-id=\"…\"` attribute",
    "  off the `<speech>` wrapper of the message you mean — never fabricate",
    "  it. Claude can't listen to audio itself; use this when the exact audio",
    "  matters — a mangled-but-important transcription, pronunciation, tone —",
    "  not routine chat. The system's own transcript rides along automatically",
    "  so the model can flag transcription flaws; `--context` supplies",
    "  conversational background (what the message responds to), and",
    "  `--transcript` overrides the known transcription.",
    "- `bbx chat retranscribe --message <id> [--diarize] [--service <name>]` —",
    "  Re-run a specific voice message (same `--message` targeting, or",
    "  `--file <path>`) through the high-quality transcription pass",
    "  (Whisper/Voxtral; default is the box's `hqService` config). For when",
    "  the realtime transcript looks wrong and you just need the correct",
    "  text — cheaper and more direct than `ask-about-audio`. Skip it when",
    "  the message's wrapper already says `stt=\"hq\"` — that text came from",
    "  the better model already, so retranscribing has nothing to add.",
    "  `--diarize` labels speakers. Prints the HQ transcript plus a `realtime-transcript:`",
    "  line for comparison. A successful run shows the corrected text on the",
    "  user's message automatically — don't paste it back unless asked.",
    "- `bbx chat get-last-audio --message <id> [--out <path>]` — Fetch the raw",
    "  recording of a specific voice message to a temp file; prints the path.",
    "  Use when you need the file itself rather than an answer about it.",
    "",
    "A bare command (no `--message`) errors — these commands never guess",
    "which recording you mean. The recording is available only while the chat",
    "tab that recorded it is open, and only for the last few voice messages",
    "(the retention window).",
    "",
  ];
}
