// AUTOGENERATED — DO NOT EDIT.
// Generated by bin/snapshot-clerk-contract.ts (pnpm snapshot:clerk-contract).
// Source of truth: callback-box/src/webapp/trpc/routers/clerk-contract.ts.
// Change the leaf schema and regenerate; never hand-edit this file.

/** Request body for `clerk.commentary`. */
export interface CommentaryPayload {
  url: string;
  title: string;
  siteName?: string;
  byline?: string;
  excerpt?: string;
  readableMarkdown: string;
  frozenHtml?: string;
  destinationDir?: string;
  timestamp?: string;
}

/** Result of a successful `clerk.commentary` capture. */
export interface CommentaryResult {
  created: string[];
  open: string;
}

/** A single landmark commentary destination. */
export interface CommentaryDestination {
  dir: string;
  label: string;
  symbol: string | null;
}
