// AUTOGENERATED — DO NOT EDIT.
// Generated by bin/snapshot-clerk-contract.ts (pnpm snapshot:clerk-contract).
// Source of truth: callback-box/src/webapp/trpc/routers/clerk-contract.ts.
// Change the leaf schema and regenerate; never hand-edit this file.

/** Request body for `clerk.commentary`. */
export interface CommentaryPayload {
  url: string;
  title: string;
  siteName?: string;
  byline?: string;
  excerpt?: string;
  readableMarkdown: string;
  frozenHtml?: string;
  destinationDir?: string;
  timestamp?: string;
}

/** Result of a successful `clerk.commentary` capture. */
export interface CommentaryResult {
  created: string[];
  open: string;
}

/** A single landmark commentary destination. */
export interface CommentaryDestination {
  dir: string;
  label: string;
  symbol: string | null;
}

/** Captured tabs and their proposed arrangement. */
export interface TabArrangementPayload {
  transferId: string;
  scope: "current-window" | "all-windows";
  capturedAt: string;
  source: {
    windows: Array<{
      id: string;
      tabs: Array<{
        id: string;
        title: string;
        url: string;
        pinned: boolean;
      }>;
    }>;
  };
  proposal: {
    windows: Array<{
      id: string;
      tabs: string[];
    }>;
    close: string[];
  };
}

/** Result of accepting a tab arrangement into the box. */
export interface TabArrangementResult {
  card: string;
  open: string;
  transferId: string;
}
