/**
 * `bakeoff summarize`: turn a judged run into tables (<run>/summary.md).
 * The dated report is written by hand around them.
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  type CallRecord,
  type Judged,
  type RawRun,
  callKey,
  checksFor,
  loadCorpus,
  modelLabel,
  readJson,
  sampleById,
  servedAs,
} from "./lib.ts";

const pct = (n: number, d: number): string => (d ? `${Math.round((100 * n) / d)}%` : "—");

function quantile(xs: number[], q: number): number {
  const s = [...xs].sort((a, b) => a - b);
  return s[Math.min(s.length - 1, Math.floor(q * s.length))] ?? 0;
}

/** Case, punctuation, curly quotes, and bracketed annotations removed; digits the corpus uses spelled out. */
export function normalizeWords(text: string): string[] {
  return text
    .toLowerCase()
    .replace(/\[[^\]]*\]/g, " ")
    .replace(/[’‘]/g, "'")
    .replace(/\b10\b/g, "ten")
    .replace(/\b7\b/g, "siete")
    .replace(/[^\p{L}\p{N}' ]+/gu, " ")
    .split(/\s+/)
    .filter(Boolean);
}

function editDistance(a: string[], b: string[]): number {
  let prev = Array.from({ length: b.length + 1 }, (_, j) => j);
  for (let i = 1; i <= a.length; i++) {
    const cur = [i];
    for (let j = 1; j <= b.length; j++) {
      cur[j] = Math.min((prev[j] ?? 0) + 1, (cur[j - 1] ?? 0) + 1, (prev[j - 1] ?? 0) + (a[i - 1] === b[j - 1] ? 0 : 1));
    }
    prev = cur;
  }
  return prev[b.length] ?? 0;
}

/** Sample id → transcript, for one call. */
function transcripts(call: CallRecord): Record<string, string> {
  if (call.mode === "transcribe") return { [Object.values(call.labels)[0] ?? ""]: call.text ?? "" };
  try {
    const parsed = JSON.parse(call.text ?? "") as { recordings?: { label?: string; transcript?: string }[] };
    const out: Record<string, string> = {};
    for (const r of parsed.recordings ?? []) {
      const id = r.label ? call.labels[r.label.replace(/^Recording\s+/i, "").trim()] : undefined;
      if (id) out[id] = r.transcript ?? "";
    }
    return out;
  } catch {
    return {};
  }
}

export function summarizeCommand(opts: { run: string }): boolean {
  const corpus = loadCorpus();
  const run = readJson<RawRun>(join(opts.run, "raw.json"));
  const judged = readJson<Judged>(join(opts.run, "judged.json"));
  const calls = run.calls.filter((c) => !c.error);
  const models = [...new Set(calls.map(modelLabel))];
  const blindModels = models.filter((m) => calls.some((c) => modelLabel(c) === m && c.mode === "blind"));
  const lines: string[] = [`# Summary tables — ${run.date}`, "", `Generated by \`summarize.ts\` (corpus v${run.corpusVersion}); do not edit by hand.`, ""];

  // Problems that make the tables below incomplete or mislabeled come first.
  const failed = run.calls.filter((c) => c.error).length;
  const unjudged = calls.filter((c) => c.mode === "blind" && !judged[callKey(c)]).length;
  if (failed) lines.push(`**Warning:** ${failed} failed call(s) are excluded; re-run \`run\` to retry them.`, "");
  if (unjudged) lines.push(`**Warning:** ${unjudged} answer(s) have no verdict and are missing from the pass rates; re-run \`judge\`.`, "");
  const served = new Map<string, Set<string>>();
  for (const c of calls) {
    const as = servedAs(c);
    if (as) served.set(modelLabel(c), (served.get(modelLabel(c)) ?? new Set()).add(as));
  }
  for (const [m, as] of served) {
    lines.push(`**Warning:** requests for ${m} were answered by ${[...as].join(", ")}. Its rows measure that model.`, "");
  }

  // Capability pass rates over scored checks, all repeats pooled.
  lines.push("## Scored checks by capability", "", "Pass rate over every scored check and every repeat.", "");
  lines.push(`| Model | ${corpus.capabilities.join(" | ")} | All scored |`, `|---|${corpus.capabilities.map(() => "---:").join("|")}|---:|`);
  for (const m of blindModels) {
    const tally: Record<string, [number, number]> = {};
    for (const c of calls.filter((x) => modelLabel(x) === m && x.mode === "blind")) {
      const verdicts = judged[callKey(c)] ?? [];
      for (const check of checksFor(corpus, c.task)) {
        if (check.scored === false) continue;
        const v = verdicts.find((x) => x.id === check.id);
        if (!v) continue;
        for (const key of [check.capability, "all"]) {
          const t = (tally[key] ??= [0, 0]);
          t[0] += v.pass ? 1 : 0;
          t[1] += 1;
        }
      }
    }
    const cell = (k: string): string => {
      const t = tally[k];
      return t ? `${pct(t[0], t[1])} (${t[0]}/${t[1]})` : "—";
    };
    lines.push(`| ${m} | ${corpus.capabilities.map(cell).join(" | ")} | **${cell("all")}** |`);
  }

  // Per-check matrix.
  lines.push("", "## Every check", "", "Passes / repeats. `*` marks an unscored check.", "");
  lines.push(`| Task | Check | ${blindModels.join(" | ")} |`, `|---|---|${blindModels.map(() => "---:").join("|")}|`);
  const tasks = corpus.groups.map((g) => g.id);
  for (const task of tasks) {
    for (const check of checksFor(corpus, task)) {
      const cells = blindModels.map((m) => {
        const rs = calls.filter((c) => modelLabel(c) === m && c.mode === "blind" && c.task === task);
        const passes = rs.filter((c) => judged[callKey(c)]?.find((v) => v.id === check.id)?.pass).length;
        return rs.length ? `${passes}/${rs.length}` : "—";
      });
      lines.push(`| ${task} | ${check.id}${check.scored === false ? "*" : ""} | ${cells.join(" | ")} |`);
    }
  }

  // Repeat consistency.
  lines.push("", "## Repeat consistency", "", "Share of checks where repeat 1 and repeat 2 got the same verdict.", "");
  lines.push("| Model | Agreement |", "|---|---:|");
  for (const m of blindModels) {
    let same = 0;
    let total = 0;
    for (const c1 of calls.filter((c) => modelLabel(c) === m && c.mode === "blind" && c.repeat === 1)) {
      const c2 = calls.find((c) => modelLabel(c) === m && c.mode === "blind" && c.task === c1.task && c.repeat === 2);
      if (!c2) continue;
      for (const v1 of judged[callKey(c1)] ?? []) {
        const v2 = judged[callKey(c2)]?.find((v) => v.id === v1.id);
        if (!v2) continue;
        total++;
        if (v1.pass === v2.pass) same++;
      }
    }
    lines.push(`| ${m} | ${total ? `${pct(same, total)} (${same}/${total})` : "single run"} |`);
  }

  // Intended-script WER over the initial set's 19 speech clips, as in 2026-08.
  const speechIds = corpus.groups
    .filter((g) => g.phase === "initial")
    .flatMap((g) => g.samples)
    .filter((id) => !id.startsWith("vocal-"))
    .filter((id) => sampleById(corpus, id).capture);
  lines.push("", "## Intended-script word error rate", "", `Initial-set speech clips (${speechIds.length}), normalized as in 2026-08; repeats pooled. Performed fillers and reductions count as errors, so this favors normalizing models.`, "");
  lines.push("| Model | WER | Exact matches | Unparsed |", "|---|---:|---:|---:|");
  for (const m of models) {
    let edits = 0;
    let words = 0;
    let exact = 0;
    let clips = 0;
    let unparsed = 0;
    for (const c of calls.filter((x) => modelLabel(x) === m && (x.mode === "transcribe" || (corpus.groups.find((g) => g.id === x.task)?.prompt ?? "blind") === "blind"))) {
      const found = transcripts(c);
      for (const id of Object.values(c.labels)) {
        if (!speechIds.includes(id)) continue;
        const text = found[id];
        if (text === undefined) {
          unparsed++;
          continue;
        }
        const ref = normalizeWords(sampleById(corpus, id).words ?? "");
        const hyp = normalizeWords(text);
        const d = editDistance(ref, hyp);
        edits += d;
        words += ref.length;
        clips++;
        if (d === 0) exact++;
      }
    }
    lines.push(`| ${m} | ${words ? `${((100 * edits) / words).toFixed(1)}%` : "—"} | ${exact}/${clips} | ${unparsed} |`);
  }

  // Invented speech: any words in a transcript of a synthetic (speech-free) sample. Deterministic; no judge.
  const syntheticIds = corpus.samples.filter((s) => s.synthetic).map((s) => s.id);
  lines.push("", "## Invented speech on synthetic audio", "", "Transcripts of speech-free synthetic clips that contain any words (bracketed annotations ignored), repeats pooled.", "");
  lines.push("| Model | Invented speech | Unparsed | Examples |", "|---|---:|---:|---|");
  for (const m of models) {
    let invented = 0;
    let total = 0;
    const examples = new Set<string>();
    let unparsed = 0;
    for (const c of calls.filter((x) => modelLabel(x) === m && (x.mode === "transcribe" || (corpus.groups.find((g) => g.id === x.task)?.prompt ?? "blind") === "blind"))) {
      const found = transcripts(c);
      for (const id of Object.values(c.labels)) {
        if (!syntheticIds.includes(id)) continue;
        const text = found[id];
        if (text === undefined) {
          unparsed++;
          continue;
        }
        total++;
        if (normalizeWords(text).length) {
          invented++;
          examples.add(text.trim());
        }
      }
    }
    const shown = [...examples].slice(0, 3).map((t) => `“${t}”`).join(", ");
    lines.push(`| ${m} | ${total ? `${invented}/${total}` : "—"} | ${unparsed} | ${shown} |`);
  }

  // Non-speech hallucination for transcription-only models.
  const transcribeModels = models.filter((m) => calls.some((c) => modelLabel(c) === m && c.mode === "transcribe"));
  if (transcribeModels.length) {
    lines.push("", "## Transcription-only models on non-speech clips", "");
    const nonSpeech = ["vocal-cough", "vocal-laugh", ...corpus.samples.filter((s) => s.synthetic).map((s) => s.id)];
    lines.push(`| Model | ${nonSpeech.join(" | ")} |`, `|---|${nonSpeech.map(() => "---").join("|")}|`);
    for (const m of transcribeModels) {
      const cells = nonSpeech.map((id) => {
        const c = calls.find((x) => modelLabel(x) === m && x.task === id);
        return c ? `\`${JSON.stringify(c.text ?? "").slice(1, -1) || "(empty)"}\`` : "—";
      });
      lines.push(`| ${m} | ${cells.join(" | ")} |`);
    }
  }

  // Latency and cost.
  lines.push("", "## Latency and cost", "", "Per call. Latency is the final attempt only, excluding rate-limit waits. A protocol pass is every task once (one call per group, or one per clip for transcription-only models). Cost is list price from token usage (OpenRouter: billed cost).", "");
  lines.push("| Model | Median latency | p90 latency | Mean cost/call | Cost per protocol pass |", "|---|---:|---:|---:|---:|");
  for (const m of models) {
    const cs = calls.filter((c) => modelLabel(c) === m);
    const lat = cs.map((c) => c.latencyMs / 1000);
    if (cs.some((c) => c.costUsd === undefined)) {
      lines.push(`| ${m} | ${quantile(lat, 0.5).toFixed(1)} s | ${quantile(lat, 0.9).toFixed(1)} s | unknown | unknown |`);
      continue;
    }
    const costs = cs.map((c) => c.costUsd ?? 0);
    const total = costs.reduce((a, b) => a + b, 0);
    // Tasks can have different repeat counts, so average per task, then sum.
    const perTask = new Map<string, number[]>();
    for (const c of cs) perTask.set(c.task, [...(perTask.get(c.task) ?? []), c.costUsd ?? 0]);
    const passCost = [...perTask.values()].reduce((sum, xs) => sum + xs.reduce((a, b) => a + b, 0) / xs.length, 0);
    lines.push(
      `| ${m} | ${quantile(lat, 0.5).toFixed(1)} s | ${quantile(lat, 0.9).toFixed(1)} s | $${(total / cs.length).toFixed(4)} | $${passCost.toFixed(3)} |`,
    );
  }
  lines.push("");
  writeFileSync(join(opts.run, "summary.md"), lines.join("\n"));
  console.log(`wrote ${join(opts.run, "summary.md")}`);
  return true;
}
