#!/usr/bin/env tsx
/**
 * Prompt Report — generates a Markdown document listing every prompt,
 * instruction, and rule in the system, with context about when each is used.
 *
 * Usage:
 *   pnpm prompt-report
 *   pnpm prompt-report --output docs/prompts.md
 */

import * as fs from "node:fs/promises";
import * as path from "node:path";
import { PACKAGE_ROOT } from "../lib/package-root.js";
import { wordCount } from "./lib/context-assembly.js";
import { collectPrompts, type PromptEntry } from "./lib/prompt-inventory.js";

// ─── Helpers ────────────────────────────────────────────────────────

function lineCount(text: string): number {
  return text.split("\n").length;
}

function fencePrompt(text: string): string {
  // Use a fenced block that won't collide with content
  const fence = text.includes("````") ? "`````" : "````";
  return `${fence}\n${text}\n${fence}`;
}

// ─── Generate markdown ──────────────────────────────────────────────

function generateMarkdown(entries: PromptEntry[]): string {
  const lines: string[] = [];
  const now = new Date().toISOString().slice(0, 19).replace("T", " ");

  lines.push("# Prompt Report");
  lines.push("");
  lines.push(`Generated: ${now}`);
  lines.push("");
  lines.push("This document lists every prompt, instruction, and rule in the callback-box system.");
  lines.push("It is auto-generated by `pnpm prompt-report` — do not edit by hand.");
  lines.push("");

  // Table of contents
  lines.push("## Table of Contents");
  lines.push("");

  // Group entries by category
  const categories = [
    { name: "Agent System Prompts", prefix: ["Reactor", "Chat", "Commit"] },
    { name: "Job-Specific Prompts", prefix: ["News", "Feedback", "Guide Revision"] },
    { name: "Schema Instructions", prefix: ["Schema:"] },
    { name: "Connector Rules", prefix: ["Connector"] },
    { name: "Procedure Templates", prefix: ["Procedure:"] },
    { name: "Procedure Infrastructure", prefix: ["Procedure Context"] },
  ];

  for (const cat of categories) {
    const catEntries = entries.filter((e) =>
      cat.prefix.some((p) => e.title.startsWith(p))
    );
    if (catEntries.length === 0) continue;

    lines.push(`### ${cat.name} (${catEntries.length})`);
    lines.push("");
    for (const entry of catEntries) {
      const anchor = entry.title.toLowerCase().replace(/[^\da-z]+/g, "-").replace(/-+$/, "");
      const words = wordCount(entry.text);
      lines.push(`- [${entry.title}](#${anchor}) — ${words} words`);
    }
    lines.push("");
  }

  // Totals
  const totalWords = entries.reduce((sum, e) => sum + wordCount(e.text), 0);
  const totalEntries = entries.length;
  lines.push(`**Total: ${totalEntries} prompts/instructions, ~${totalWords.toLocaleString()} words**`);
  lines.push("");
  lines.push("---");
  lines.push("");

  // Full entries
  for (const entry of entries) {
    lines.push(`## ${entry.title}`);
    lines.push("");
    lines.push(`**Source:** \`${entry.source}\``);
    lines.push("");
    lines.push(`**Scope:** ${entry.scope}`);
    lines.push("");
    lines.push(`**Size:** ${wordCount(entry.text)} words, ${lineCount(entry.text)} lines`);
    lines.push("");
    lines.push(fencePrompt(entry.text));
    lines.push("");
    lines.push("---");
    lines.push("");
  }

  return lines.join("\n");
}

// ─── Main ───────────────────────────────────────────────────────────

const args = process.argv.slice(2);
let outputPath: string | null = null;

for (let i = 0; i < args.length; i++) {
  const next = args[i + 1];
  if (args[i] === "--output" && next) {
    outputPath = next;
    i++;
  }
}

const entries = await collectPrompts();
const markdown = generateMarkdown(entries);

if (outputPath) {
  const resolved = path.resolve(outputPath);
  await fs.writeFile(resolved, markdown);
  console.log(`Wrote ${entries.length} prompts to ${resolved}`);
} else {
  // Default: write to docs/prompts.md
  const defaultPath = path.join(PACKAGE_ROOT, "docs", "prompts.md");
  await fs.writeFile(defaultPath, markdown);
  console.log(`Wrote ${entries.length} prompts to docs/prompts.md`);
}
