// Authored docs (plan: "Sources", Authored row): the spine (numbered files
// directly under site/docs/), directory content pages, and the per-directory
// `index.md` stubs (frontmatter `description:` only — the *published*
// index.md is generated by docs-index.ts, never authored). `site/docs/README.md`
// is special: it supplies the llms.txt one-line summary and preamble, and is
// never itself published as a doc. A `README.md` inside ANY directory works
// the same way for that directory (one-line `description:` plus an optional
// `start-here:` list, both consumed by an entry file beside `docs-index.ts`'s
// llms.txt renderer) — never published as a page either.

import fs from "node:fs/promises";
import path from "node:path";
import { z } from "zod";
import { comparedFrontmatterSchema, type PublishedDoc } from "./docs-types.js";
import { parseFrontmatter } from "./render.js";
import { scrubText } from "./docs-scrub.js";

export class DocsAuthoredError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "DocsAuthoredError";
  }
}

const docFrontmatterSchema = z
  .object({
    description: z.string().min(1),
    compared: comparedFrontmatterSchema.optional(),
  })
  .strict();

const stubFrontmatterSchema = z.object({ description: z.string().min(1) }).strict();

const readmeFrontmatterSchema = z
  .object({ description: z.string().min(1), "start-here": z.array(z.string().min(1)).min(1).optional() })
  .strict();

export interface DirReadme {
  summary: string;
  preamble: string;
  startHere: readonly string[] | undefined;
}

const SPINE_RE = /^\d{2}-[\w-]+\.md$/;

async function walkMarkdown(dir: string, base: string): Promise<string[]> {
  let entries;
  try {
    entries = await fs.readdir(dir, { withFileTypes: true });
  } catch (_e) {
    return []; // no site/docs/ yet — nothing authored, which is legal mid-build
  }
  const out: string[] = [];
  for (const entry of entries) {
    if (entry.isDirectory()) {
      out.push(...(await walkMarkdown(path.join(dir, entry.name), `${base}${entry.name}/`)));
    } else if (entry.isFile() && entry.name.endsWith(".md")) {
      out.push(`${base}${entry.name}`);
    }
  }
  return out;
}

export interface AuthoredCorpus {
  docs: PublishedDoc[];
  /** dir (posix, no trailing slash, "" never appears — spine has no index) -> purpose line. */
  indexPurposes: Map<string, string>;
  readme: { summary: string; preamble: string } | undefined;
  /** Non-root README.md files, keyed by their directory (posix, no trailing slash). */
  dirReadmes: Map<string, DirReadme>;
}

/** Load every authored doc under `docsDir` (site/docs/). */
export async function loadAuthoredDocs(params: { docsDir: string; repoRoot: string }): Promise<AuthoredCorpus> {
  const { docsDir, repoRoot } = params;
  const rels = await walkMarkdown(docsDir, "");
  const docs: PublishedDoc[] = [];
  const indexPurposes = new Map<string, string>();
  const dirReadmes = new Map<string, DirReadme>();
  let readme: { summary: string; preamble: string } | undefined;

  for (const rel of rels) {
    const raw = await fs.readFile(path.join(docsDir, rel), "utf8");
    const label = `site/docs/${rel}`;
    scrubText(raw, { sourceLabel: label, repoRoot, blocklist: true });

    if (rel === "README.md") {
      const { frontmatter, body } = parseFrontmatter(raw, { file: label, schema: stubFrontmatterSchema });
      readme = { summary: frontmatter.description, preamble: body.trim() };
      continue;
    }
    if (path.posix.basename(rel) === "README.md") {
      const { frontmatter, body } = parseFrontmatter(raw, { file: label, schema: readmeFrontmatterSchema });
      const dir = path.posix.dirname(rel);
      dirReadmes.set(dir, {
        summary: frontmatter.description,
        preamble: body.trim(),
        startHere: frontmatter["start-here"],
      });
      continue;
    }
    if (path.posix.basename(rel) === "index.md") {
      const { frontmatter } = parseFrontmatter(raw, { file: label, schema: stubFrontmatterSchema });
      const dir = path.posix.dirname(rel);
      indexPurposes.set(dir === "." ? "" : dir, frontmatter.description);
      continue;
    }

    const dir = path.posix.dirname(rel);
    const isSpine = dir === "." && SPINE_RE.test(rel);
    if (dir === "." && !isSpine) {
      throw new DocsAuthoredError(`${label}: files directly under site/docs/ must be numbered spine files (NN-name.md)`);
    }
    const { frontmatter, body } = parseFrontmatter(raw, { file: label, schema: docFrontmatterSchema });
    const underCompared = dir === "compared" || dir.startsWith("compared/");
    if (underCompared && frontmatter.compared === undefined) {
      throw new DocsAuthoredError(`${label}: pages under compared/ require a "compared:" frontmatter block`);
    }
    if (!underCompared && frontmatter.compared !== undefined) {
      throw new DocsAuthoredError(`${label}: "compared:" frontmatter is only for pages under compared/`);
    }
    docs.push({
      publishPath: rel,
      kind: "authored",
      description: frontmatter.description,
      body: body.trim(),
      sourceLabel: label,
      // exactOptionalPropertyTypes: only set the key when a value exists.
      ...(frontmatter.compared !== undefined ? { compared: frontmatter.compared } : {}),
    });
  }
  return { docs, indexPurposes, readme, dirReadmes };
}
