/**
 * Box directory structure operations.
 *
 * Creates and manages the standard directory layout for a callback box.
 */

import * as fs from "node:fs/promises";
import * as path from "node:path";
import { BOX_DIRS, BOX_MARKER, boxPath } from "../cli/lib/paths.js";
import { initRepo, stageAll, commit, isRepo } from "../cli/lib/git.js";
import { createInitialGuideTemplate } from "../schemas/guide.js";

const __dirname = import.meta.dirname;

export interface InitOptions {
  /** Skip git initialization */
  skipGit?: boolean | undefined;
  /** Initial branch name */
  branch?: string | undefined;
}

export interface InitResult {
  /** Whether this was a fresh init or an update of an existing box */
  isUpdate: boolean;
}

/**
 * Initialize a new callback box or update an existing one.
 *
 * On a fresh init: creates directories, marker, .gitignore, git repo, initial commit.
 * On an existing box: ensures directories exist, updates .gitignore.
 *
 * @param boxRoot - Directory to initialize (will be created if needed)
 * @param options - Initialization options
 */
export async function initBox(boxRoot: string, options: InitOptions = {}): Promise<InitResult> {
  const resolvedRoot = path.resolve(boxRoot);

  // Create root directory if needed
  await fs.mkdir(resolvedRoot, { recursive: true });

  // Check if already initialized
  const markerPath = path.join(resolvedRoot, BOX_MARKER);
  const isUpdate = await isValidBox(resolvedRoot);

  // Create all standard directories (safe to re-run)
  await ensureDirectories(resolvedRoot);

  if (!isUpdate) {
    // Create marker file with metadata
    const marker = {
      version: "1.0.0",
      created: new Date().toISOString(),
    };
    await fs.writeFile(markerPath, JSON.stringify(marker, null, 2) + "\n");
  }

  // Always write .gitattributes (LFS rules)
  const gitattributes = `# Track frozen page captures in Git LFS
*.frozen filter=lfs diff=lfs merge=lfs -text
`;
  await fs.writeFile(path.join(resolvedRoot, ".gitattributes"), gitattributes);

  // Always write .gitignore (keep in sync with cb version)
  const gitignore = `# Callback Box .gitignore
# Lock files
.cb-lock

# Local config (credentials, etc.)
config/connectors/*.secret.*

# Server PID file
.cb-serve.pid

# Generated agent docs (regenerated by cb init/reactor)
.callback-box/
docs/generated/

# Temporary files
*.tmp
*.swp
*~
`;
  await fs.writeFile(path.join(resolvedRoot, ".gitignore"), gitignore);

  // Initialize git repo (only on fresh init)
  if (!options.skipGit && !isUpdate) {
    const isExistingRepo = await isRepo(resolvedRoot);
    if (!isExistingRepo) {
      await initRepo(resolvedRoot, options.branch ?? "main");
    }

    // Initial commit
    await stageAll(resolvedRoot);
    await commit(resolvedRoot, {
      message: "Initialize callback box",
      trailers: {
        "Created-By": "cb init",
      },
    });
  }

  return { isUpdate };
}

/**
 * Ensure all standard directories exist.
 *
 * @param boxRoot - The box root directory
 */
export async function ensureDirectories(boxRoot: string): Promise<void> {
  const dirs = Object.values(BOX_DIRS);

  for (const dir of dirs) {
    const fullPath = boxPath(boxRoot, dir);
    await fs.mkdir(fullPath, { recursive: true });

    // Create .gitkeep to preserve empty directories
    const gitkeep = path.join(fullPath, ".gitkeep");
    try {
      await fs.access(gitkeep);
    } catch {
      await fs.writeFile(gitkeep, "");
    }
  }
}

/**
 * Check if a directory is a valid callback box.
 *
 * @param boxRoot - Directory to check
 * @returns Whether it's a valid box
 */
export async function isValidBox(boxRoot: string): Promise<boolean> {
  const markerPath = path.join(boxRoot, BOX_MARKER);
  try {
    await fs.access(markerPath);
    return true;
  } catch {
    return false;
  }
}

/**
 * Get box metadata from the marker file.
 *
 * @param boxRoot - The box root directory
 * @returns Box metadata or null if not a valid box
 */
export async function getBoxMetadata(
  boxRoot: string
): Promise<{ version: string; created: string } | null> {
  const markerPath = path.join(boxRoot, BOX_MARKER);
  try {
    const content = await fs.readFile(markerPath, "utf-8");
    return JSON.parse(content) as { version: string; created: string };
  } catch {
    return null;
  }
}

/**
 * Install workflow templates into a box.
 *
 * On fresh install: copies template workflow cards to config/workflows/.
 * On update: if the box's copy matches the previously installed version,
 * updates it. If the box's copy has been modified, writes the new version
 * as a .orig-workflow.card file for manual merging.
 *
 * @returns List of installed/updated workflow names
 */
export async function installWorkflows(boxRoot: string): Promise<string[]> {
  // Templates live alongside the compiled JS: ../../templates/workflows/
  const templatesDir = path.join(__dirname, "..", "..", "templates", "workflows");
  const targetDir = path.join(boxRoot, BOX_DIRS.workflows);

  await fs.mkdir(targetDir, { recursive: true });

  let templateFiles: string[];
  try {
    templateFiles = (await fs.readdir(templatesDir)).filter((f) =>
      f.endsWith(".workflow.card")
    );
  } catch {
    // No templates directory — nothing to install
    return [];
  }

  const installed: string[] = [];

  for (const file of templateFiles) {
    const templateContent = await fs.readFile(
      path.join(templatesDir, file),
      "utf-8"
    );
    const targetPath = path.join(targetDir, file);

    let existingContent: string | null = null;
    try {
      existingContent = await fs.readFile(targetPath, "utf-8");
    } catch {
      // File doesn't exist yet
    }

    if (existingContent === null) {
      // Fresh install
      await fs.writeFile(targetPath, templateContent);
      installed.push(file);
    } else if (existingContent === templateContent) {
      // Already up to date
    } else {
      // Box copy differs from template — write as .orig for manual merge
      const origName = file.replace(".workflow.card", ".orig-workflow.card");
      await fs.writeFile(path.join(targetDir, origName), templateContent);
      installed.push(`${origName} (update available)`);
    }
  }

  return installed;
}

/** Known guide domains that get default templates */
const GUIDE_DOMAINS = ["news", "intake", "calendar"];

/**
 * Strip ISO timestamps from guide content so we can compare
 * template output across runs (created-at changes each time).
 */
function normalizeGuideForComparison(content: string): string {
  return content.replace(
    / (created-at|updated-at|added-at)="[^"]*"/g,
    ""
  );
}

/**
 * Install default guide cards into a box.
 *
 * On fresh install: writes default guide cards to config/.
 * On update: if the box's copy matches the template (ignoring timestamps),
 * overwrites it with the latest template. If the user has modified the guide,
 * writes the new version as a .orig-guide.card for manual merging.
 *
 * Skips any domain where a guide already exists from migration (e.g., news
 * guide migrated from the legacy news-guide format).
 *
 * @returns List of installed/updated guide names
 */
export async function installGuides(boxRoot: string): Promise<string[]> {
  const configDir = path.join(boxRoot, "config");
  await fs.mkdir(configDir, { recursive: true });

  const installed: string[] = [];

  for (const domain of GUIDE_DOMAINS) {
    const fileName = `${domain}.guide.card`;
    const targetPath = path.join(configDir, fileName);
    const templateContent = createInitialGuideTemplate({ name: domain });

    let existingContent: string | null = null;
    try {
      existingContent = await fs.readFile(targetPath, "utf-8");
    } catch {
      // File doesn't exist yet
    }

    if (existingContent === null) {
      // Fresh install
      await fs.writeFile(targetPath, templateContent);
      installed.push(fileName);
    } else if (
      normalizeGuideForComparison(existingContent) ===
      normalizeGuideForComparison(templateContent)
    ) {
      // Template content matches (user hasn't modified it) — overwrite with latest
      await fs.writeFile(targetPath, templateContent);
    } else {
      // User has modified the guide — write .orig for manual merge
      const origName = `${domain}.orig-guide.card`;
      await fs.writeFile(path.join(configDir, origName), templateContent);
      installed.push(`${origName} (update available)`);
    }
  }

  return installed;
}

