export const THEME_CATALOG = [
  {
    name: "plain",
    label: "Flat",
    stocks: ["neutral"],
    defaultStock: "neutral",
    quoteTreatment: "plain",
    blockquoteTreatment: "plain",
    chrome: true,
    systemOnly: false,
    cardThemes: ["plain", "paper", "post-it"],
  },
  {
    name: "spectrum",
    label: "Spectrum",
    stocks: ["gradient"],
    defaultStock: "gradient",
    quoteTreatment: "plain",
    blockquoteTreatment: "plain",
    chrome: true,
    systemOnly: true,
    cardThemes: ["plain", "electric-playground", "daydream", "post-it"],
  },
  {
    name: "paper",
    label: "Paper",
    stocks: ["cream", "manila", "blue"],
    defaultStock: "cream",
    quoteTreatment: "layered",
    blockquoteTreatment: "layered",
    chrome: true,
    systemOnly: false,
    cardThemes: ["paper", "post-it", "letter-set", "selvedge"],
  },
  {
    name: "post-it",
    label: "Sticky note",
    stocks: ["yellow", "rose", "mint"],
    defaultStock: "yellow",
    quoteTreatment: "layered",
    blockquoteTreatment: "layered",
    chrome: false,
    systemOnly: false,
  },
  {
    name: "candy",
    label: "Candy",
    stocks: ["strawberry"],
    defaultStock: "strawberry",
    quoteTreatment: "plain",
    blockquoteTreatment: "plain",
    chrome: true,
    systemOnly: true,
    cardThemes: ["letter-set", "post-it", "daydream"],
  },
  {
    name: "letter-set",
    label: "Letter set",
    stocks: ["strawberry", "lemon", "sky"],
    defaultStock: "strawberry",
    quoteTreatment: "layered",
    blockquoteTreatment: "layered",
    chrome: false,
    systemOnly: false,
  },
  {
    name: "harlequin",
    composition: "expressive",
    label: "Harlequin",
    stocks: ["pigment"],
    defaultStock: "pigment",
    quoteTreatment: "inset",
    blockquoteTreatment: "inset",
    chrome: true,
    systemOnly: false,
    cardThemes: ["harlequin", "paper", "far-horizon"],
  },
  {
    name: "electric-playground",
    composition: "expressive",
    label: "Electric Playground",
    stocks: ["prism"],
    defaultStock: "prism",
    quoteTreatment: "inset",
    blockquoteTreatment: "inset",
    chrome: true,
    systemOnly: false,
    cardThemes: ["electric-playground", "blacklight", "post-it"],
  },
  {
    name: "daydream",
    composition: "expressive",
    label: "Daydream",
    stocks: ["cloud"],
    defaultStock: "cloud",
    quoteTreatment: "inset",
    blockquoteTreatment: "inset",
    chrome: true,
    systemOnly: false,
    cardThemes: ["daydream", "letter-set", "plain"],
  },
  {
    name: "selvedge",
    composition: "expressive",
    label: "Selvedge",
    stocks: ["wool"],
    defaultStock: "wool",
    quoteTreatment: "inset",
    blockquoteTreatment: "inset",
    chrome: true,
    systemOnly: false,
    cardThemes: ["selvedge", "paper", "golden-hour"],
  },
  {
    name: "footlights",
    composition: "expressive",
    label: "Footlights",
    stocks: ["marquee"],
    defaultStock: "marquee",
    quoteTreatment: "inset",
    blockquoteTreatment: "inset",
    chrome: true,
    systemOnly: false,
    cardThemes: ["footlights", "paper", "harlequin"],
  },
  {
    name: "overpass",
    composition: "expressive",
    label: "Overpass",
    stocks: ["silhouette"],
    defaultStock: "silhouette",
    quoteTreatment: "inset",
    blockquoteTreatment: "inset",
    chrome: true,
    systemOnly: false,
    cardThemes: ["overpass", "post-it", "far-horizon"],
  },
  {
    name: "golden-hour",
    composition: "expressive",
    label: "Golden Hour",
    stocks: ["canopy"],
    defaultStock: "canopy",
    quoteTreatment: "inset",
    blockquoteTreatment: "inset",
    chrome: true,
    systemOnly: false,
    cardThemes: ["golden-hour", "far-horizon", "paper"],
  },
  {
    name: "blacklight",
    composition: "expressive",
    label: "Blacklight",
    stocks: ["ink"],
    defaultStock: "ink",
    quoteTreatment: "inset",
    blockquoteTreatment: "inset",
    chrome: true,
    systemOnly: false,
    cardThemes: ["blacklight", "electric-playground", "post-it"],
  },
  {
    name: "far-horizon",
    composition: "expressive",
    label: "Far Horizon",
    stocks: ["gouache"],
    defaultStock: "gouache",
    quoteTreatment: "inset",
    blockquoteTreatment: "inset",
    chrome: true,
    systemOnly: false,
    cardThemes: ["far-horizon", "golden-hour", "paper"],
  },
] as const;

export type ThemeDescriptor = (typeof THEME_CATALOG)[number];
export type ThemeName = ThemeDescriptor["name"];
export type ThemeStock = ThemeDescriptor["stocks"][number];

/**
 * The card themes that go with a system theme, its default first. A card with
 * no authored theme takes the default of the system theme it is shown on; the
 * picker lists the rest first. A card theme may go with several system themes.
 */
export function systemCardThemes(systemTheme: string | undefined): readonly string[] {
  const theme = THEME_CATALOG.find((item) => item.name === systemTheme);
  return theme !== undefined && "cardThemes" in theme ? theme.cardThemes : ["plain"];
}

/** Opt in to scene, control, and sheet composition tokens. */
export function themeComposition(name: string | undefined): "expressive" | undefined {
  const theme = THEME_CATALOG.find((item) => item.name === name);
  return theme !== undefined && "composition" in theme ? theme.composition : undefined;
}
