/**
 * Compose the compact agent guide (`.beebox/agent-guide.md`,
 * always loaded into context via @-include).
 *
 * Each section is a small file in this directory; the orchestrator below just
 * concatenates them in the order they appear in the rendered guide. Adding or
 * editing prose: pick the right section file. Adding a section: write a new
 * file and slot it into the array below.
 */

import type { CardSchema } from "../../cards/index.js";
import type { TemplateDefinition } from "../../schemas/templates.js";
import { cardSchemas } from "../../schemas/registry.js";
import type { ProcedureSummary, GuideSummary } from "../docs-gen/index.js";
import type { BoxShape } from "../../lib/box-shape.js";

import { directoryLayoutSection, howItemsEnterSection, boxCodeLocationSection } from "./box-shape.js";
import { keyCommandsSection } from "./commands.js";
import { proceduresSection, guidesSection } from "./extensibility.js";
import { externalToolsSection } from "./chat.js";
import {
  aboutCardsSection,
  cardTypesSection,
  questionsSection,
} from "./cards.js";
import { todosSection } from "./todos.js";
import { gitHistorySection, speakingToUserSection, whereToRecordSection } from "./behavior.js";
import { landmarksSection } from "./landmarks.js";
import { secretsSection } from "./secrets.js";
import { lawsSection } from "./laws.js";
import { quotesSection } from "./quotes.js";
import { sourceSection } from "./source.js";
import { searchSection } from "./search.js";
import { whereTheDocsAreSection } from "./where-docs.js";

export interface AgentGuideOptions {
  procedures: ProcedureSummary[];
  /** This box's physical layout. Determines whether the guide teaches the
   * package-layout code-location rules (shape 2+) or omits them entirely
   * (legacy shape 1, unchanged from before shape-awareness existed). */
  shape: BoxShape;
  allCardSchemas?: CardSchema[];
  /** The box-local schemas (a subset of `allCardSchemas`); their docs live in
   *  the box rather than the package. */
  boxCardSchemas?: CardSchema[];
  /** Templates this box's own schemas registered (see `cardTypesSection`). */
  boxTemplates?: TemplateDefinition[];
  /** Whether the engine's TypeScript source is present beside the package
   *  docs (a checkout) — a packed install ships only `dist`. Decides whether
   *  the guide offers the source as the fallback reference. */
  engineSourcePresent?: boolean;
  personalitySection?: string | undefined;
  guides?: GuideSummary[];
}

export function generateAgentGuide(options: AgentGuideOptions): string {
  const {
    procedures,
    shape,
    allCardSchemas = cardSchemas,
    boxCardSchemas = [],
    boxTemplates = [],
    engineSourcePresent = false,
    personalitySection,
    guides = [],
  } = options;

  const intro = `# Bee Box Agent Guide

This guide is for every agent working in this box — chat, background jobs, and procedure runs alike. A box is a personal workspace you operate on the user's behalf: the filesystem is the state, Git is the history, and cards are the record. The user teaches by asking, answering, and correcting; your job is to do the work and keep the record true.

(This guide is generated by \`bbx init\` — if it seems stale, re-run it.)`;

  const sections: string[] = [
    intro,
    lawsSection(),
    whereTheDocsAreSection({ engineSourcePresent }),
    speakingToUserSection(),
    aboutCardsSection(),
    cardTypesSection({ allCardSchemas, boxCardSchemas, boxTemplates }),
    questionsSection(),
    todosSection(),
    directoryLayoutSection(),
    boxCodeLocationSection(shape),
    landmarksSection(),
    howItemsEnterSection(),
    keyCommandsSection(),
    searchSection(),
    proceduresSection(procedures),
    guidesSection(guides),
    secretsSection(),
    externalToolsSection(),
    quotesSection(),
    sourceSection(),
    gitHistorySection(),
    whereToRecordSection(),
  ];

  if (personalitySection) {
    sections.push(personalitySection);
  }

  // Each section is a self-contained markdown block; normalize any trailing
  // blank line and drop empty (omitted) sections, so blocks are separated by
  // exactly one blank line.
  return sections
    .map((s) => s.replace(/\n+$/, ""))
    .filter((s) => s.length > 0)
    .join("\n\n");
}
