/**
 * General agent behavior: principles, the role of git history, and a guide to
 * choosing where to record discovered information.
 */

import { SECTION, xref } from "./sections.js";

export function generalPrinciplesSection(): string[] {
  return [
    "## General Principles",
    "",
    "- This guide and `docs/generated/` are code-generated by `cb init`. If docs seem stale, re-run `cb init` to regenerate.",
    "",
    `How cards work — frontmatter, refs, naming, attachments, and the \`cb create\` / \`cb mv\` / \`cb rm\` commands — is in ${xref(SECTION.ABOUT_CARDS)}.`,
    "",
  ];
}

export function gitHistorySection(): string[] {
  return [
    "## Git History",
    "",
    "Git history is the primary record of what happened in the box. To understand what an agent did, what was processed, or when something changed, **check `git log` first** — don't search the filesystem for clues.",
    "",
    "Commits use structured trailers (key-value metadata after the message body):",
    "",
    "| Trailer | Meaning |",
    "|---------|---------|",
    "| `Triggered-By: cb procedure` | What command/system initiated this work |",
    "| `Phase: triage` | Which phase of a pipeline (triage, fetch, analyze, brief, etc.) |",
    "| `Session: <uuid>` | Links the commit to a specific agent session |",
    "| `Job-Type: <type>` | Card type of the job that was finished |",
    "| `Fallback: true` | Agent didn't commit; system made a fallback commit |",
    "| `Commit-Source: procedure-fallback` | Procedure engine's fallback commit |",
    "| `Created-By: <connector>` | Connector that created the content (e.g., gmail, telegram) |",
    "",
    "Useful queries:",
    "- `git log --oneline -20` — recent activity overview",
    "- `git log --all --grep='Phase: brief'` — find all brief-creation commits",
    "- `git log -- box/inbox/` — history of a specific directory",
    "- `git show <hash>` — full diff of what a commit changed",
    "",
  ];
}

export function whereToRecordSection(): string[] {
  return [
    "## Where to Record What You Find",
    "",
    "The box has its own files for capturing knowledge. Use these — they persist across agent sessions and are visible to all agents working in this box.",
    "",
    "**IMPORTANT: Do NOT use `.claude/memory/` files for box information.** The box's own files (briefing cards, other cards, guides, personality) are the correct storage. `.claude/memory/` is not shared with other agents and is not part of the box's state.",
    "",
    "### Briefing cards — core context",
    "",
    "The briefing card (`briefing.briefing.card` at the box root) is the **primary place** for situational context — what this box is for, who the key people are, and essential facts every agent needs. Edit it when you discover core information (add a new key person → also create `people/First_Last.person.card`). Its fields and tags are documented in the briefing card's own instructions (`docs/generated/card-briefing.md`); think of it as notes for a new team member.",
    "",
    "Directory briefings (`briefing.briefing.card` in any subdirectory) can explain what that directory contains.",
    "",
    "### Record / memo / bookmark cards — individual items",
    "",
    "A specific bank account, a piece of furniture, a contact's phone number. These go in `store/archive/` as cards. This is where most things you encounter belong.",
    "",
    "### Guide cards (`config/*.guide.card`) — per-domain processing rules",
    "",
    "Per-domain pipeline rules — intake, calendar review, etc. When the user says \"always do X with Y\" for a specific pipeline, update the relevant guide.",
    "",
    "### Landmark destinations — filing targets",
    "",
    "A landmark can mark its directory as a **destination** — a spot the system files things into — via a `destinations:` list in its frontmatter. Each entry's `for:` names the kinds it accepts: `[triage]` (a routing target for the intake→triage→handle pipeline; a triage destination also carries `rules:` and a `procedure: { ref }` for its handler — see `docs/plans/triage-design.md`) and/or `[commentary]` (where the clerk capture flow files web-page commentary). When the user clarifies what kind of item belongs where, update the landmark's `destinations`, not a guide card.",
    "",
    "### Personality card (`config/main.personality.card`) — voice and manner ONLY",
    "",
    "Changes to how the agent **sounds** — tone, formality, speaking voice, how proactive — go here (see the personality card's own instructions for how). Not situational context, the box's purpose, or facts about people — those are the briefing card.",
    "",
    "### Retrospective-inferred beliefs",
    "",
    "A weekly retrospective (`process-retrospective`) mines past chat sessions and writes what it learned into personality/guide cards as `source: inferred` entries. Treat those as the agent's own working hypotheses — don't promote them past `medium`, and don't use them to contradict a `user-stated` belief (that takes the boxholder's say-so). The full confidence-ladder detail lives with the retrospective procedure; run reports are in `store/reviews/retro/`.",
    "",
    "### Quick test",
    "",
    "- **What is this box about?** Who are the people? What's the situation? → briefing card (`briefing.briefing.card`)",
    "- A **discrete item** to track (an asset, a document, a contact) → card in `store/`",
    "- Changes **how the pipeline routes items** (which directory a kind of item belongs in) → a `for: [triage]` entry in that directory's landmark `destinations`",
    "- Changes **how a specific domain pipeline behaves** → the matching `config/*.guide.card`",
    "- Changes **how the agent sounds** (tone, formality, verbosity) → personality",
    "",
    "### Don't drop unexpected information",
    "",
    "When processing an item, you may encounter important information that's outside the scope of your current task — a legal deadline buried in a furniture walkthrough, an unknown contact mentioned in passing, an account number in a casual note.",
    "",
    "**Don't ignore it.** Handle it based on context:",
    "",
    "- **In a chat conversation**: mention it naturally in your response. Don't hijack the conversation for an aside, but acknowledge it and note that it might need follow-up.",
    "- **In a processing job** (an intake job, a capture-session sort, a procedure step, etc.): create a question card in `box/questions/` asking the user what to do with it. If the source item needs to stay accessible, move it to `box/inbox/unhandled/` so it doesn't get lost.",
    "- **If you're confident** about where it belongs (clear category, obvious action item), file it directly — create a record, todo, or other card in the right place.",
    "",
    "The worst outcome is silently discarding information that turns out to matter. When in doubt, ask.",
  ];
}
