/**
 * Calendar (Google Calendar two-way sync via .ics files in store/calendar/).
 */

export function calendarSection(): string[] {
  return [
    "## Calendar",
    "",
    "Calendar events live as `.ics` files in `store/calendar/`. Sync with Google Calendar is **two-way**:",
    "",
    "- **View events:** `cb calendar` shows upcoming events. `cb calendar today`, `cb calendar 2w`, etc.",
    "- **Create an event:** Write a new `.ics` file in `store/calendar/`. Next sync pushes it to Google Calendar.",
    "  - Include `X-CB-CALENDAR-ID:<calendar-id>` to target a specific calendar (defaults to primary).",
    "  - Optionally include `X-CB-REASON:<why>` and `X-CB-REF:<path>` for tracking.",
    "- **Edit an event:** Modify a tracked `.ics` file directly. Next sync pushes the changes to Google Calendar.",
    "- **Delete an event:** Add `X-CB-DELETE:<reason>` property to a tracked `.ics` file. Next sync deletes it from Google Calendar.",
    "",
    "**Timezone requirement:** Non-all-day events MUST include a VTIMEZONE component and TZID parameter on DTSTART/DTEND. Never create floating-time events — they'll be rejected. Use the box's local timezone (e.g., `America/Chicago`).",
    "",
    "Example minimal .ics for a new event:",
    "```",
    "BEGIN:VCALENDAR",
    "VERSION:2.0",
    "PRODID:-//Callback Box//EN",
    "BEGIN:VTIMEZONE",
    "TZID:America/Chicago",
    "BEGIN:STANDARD",
    "DTSTART:19701101T020000",
    "RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU",
    "TZOFFSETFROM:-0500",
    "TZOFFSETTO:-0600",
    "TZNAME:CST",
    "END:STANDARD",
    "BEGIN:DAYLIGHT",
    "DTSTART:19700308T020000",
    "RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU",
    "TZOFFSETFROM:-0600",
    "TZOFFSETTO:-0500",
    "TZNAME:CDT",
    "END:DAYLIGHT",
    "END:VTIMEZONE",
    "BEGIN:VEVENT",
    "UID:unique-id-here",
    "SUMMARY:Dentist appointment",
    "DTSTART;TZID=America/Chicago:20260401T140000",
    "DTEND;TZID=America/Chicago:20260401T150000",
    "END:VEVENT",
    "END:VCALENDAR",
    "```",
    "",
  ];
}
