/**
 * Compose the compact agent guide (`.callback-box/agent-guide.md`,
 * always loaded into context via @-include).
 *
 * Each section is a small file in this directory; the orchestrator below just
 * concatenates them in the order they appear in the rendered guide. Adding or
 * editing prose: pick the right section file. Adding a section: write a new
 * file and slot it into the array below.
 */

import type { CardSchema } from "../../cards/index.js";
import { cardSchemas } from "../../schemas/registry.js";
import type { ProcedureSummary, GuideSummary } from "../generate-docs.js";

import { directoryLayoutSection, howItemsEnterSection } from "./box-shape.js";
import { keyCommandsSection } from "./commands.js";
import { proceduresSection, guidesSection } from "./extensibility.js";
import {
  externalToolsSection,
  chatAttachmentsSection,
  selectionsSection,
} from "./chat.js";
import {
  aboutCardsSection,
  cardTypesSection,
  questionsSection,
} from "./cards.js";
import { gitHistorySection, whereToRecordSection } from "./behavior.js";
import { landmarksSection } from "./landmarks.js";
import { secretsSection } from "./secrets.js";
import { lawsSection } from "./laws.js";
import { quotesSection } from "./quotes.js";
import { sourceSection } from "./source.js";
import { searchSection } from "./search.js";

export interface AgentGuideOptions {
  procedures: ProcedureSummary[];
  allCardSchemas?: CardSchema[];
  personalitySection?: string | undefined;
  guides?: GuideSummary[];
}

export function generateAgentGuide(options: AgentGuideOptions): string {
  const {
    procedures,
    allCardSchemas = cardSchemas,
    personalitySection,
    guides = [],
  } = options;

  const lines: string[] = [
    "# Callback Box Agent Guide",
    "",
    "This guide is for every agent working in this box — chat, background jobs, and procedure runs alike. A box is a personal workspace you operate on the user's behalf: the filesystem is the state, Git is the history, and cards are the record. The user teaches by asking, answering, and correcting; your job is to do the work and keep the record true.",
    "",
    "(This guide and `docs/generated/` are generated by `cb init` — if they seem stale, re-run it.)",
    "",
    ...lawsSection(),
    ...aboutCardsSection(),
    ...cardTypesSection(allCardSchemas),
    ...questionsSection(),
    ...directoryLayoutSection(),
    ...landmarksSection(),
    ...howItemsEnterSection(),
    ...keyCommandsSection(),
    ...searchSection(),
    ...proceduresSection(procedures),
    ...guidesSection(guides),
    ...secretsSection(),
    ...externalToolsSection(),
    ...chatAttachmentsSection(),
    ...selectionsSection(),
    ...quotesSection(),
    ...sourceSection(),
    ...gitHistorySection(),
    ...whereToRecordSection(),
  ];

  if (personalitySection) {
    lines.push(personalitySection);
  }

  return lines.join("\n");
}
