/**
 * Recipe vocabulary: six body Markdoc tags that replaced the old XML
 * recipe schema. Reference for agents editing recipes.
 */

export function recipeTagsSection(): string[] {
  return [
    "## Recipe Tags",
    "",
    "Recipe cards (`*.recipe.card`) are Phase-2 cards now — identity in",
    "frontmatter (`title`, `description`, `source`, `tags`,",
    "`hero-image`), structure in the body via six Markdoc tags:",
    "",
    "- `{% ingredient amount=\"2\" unit=\"cups\" %}flour{% /ingredient %}`",
    "  — inline within a step's prose, or as a list item under",
    "  `## Ingredients`. The recipe view scales the `amount` attribute",
    "  with a `Fraction` parser (values like `1/4`, `1 1/2`, `2-3`",
    "  ranges all work).",
    "- `{% step %}First, do this thing.{% /step %}` — one step of the",
    "  recipe. The recipe view auto-numbers via CSS counter. Source has",
    "  no numbers; reorder by moving the block.",
    "- `{% yield amount=\"4\" %}4 servings{% /yield %}` — the scaling",
    "  base. `amount` is the multiplier root; the body text is human-",
    "  readable.",
    "- `{% substitution for=\"buttermilk\" %}Use milk + lemon",
    "  juice.{% /substitution %}` — optional substitution. `for` names",
    "  the ingredient or step being substituted.",
    "- `{% subrecipe ref=\"/store/recipes/sauces/Marinara.recipe.card\" %}",
    "  Use a half batch.{% /subrecipe %}` — link to a sibling recipe.",
    "  `ref` is a card path (Track 4's body ref-walker tracks it).",
    "- `{% recipe-section name=\"Sauce\" %}` — groups a sub-recipe within",
    "  a recipe (e.g. sauce + pasta in one card). Optional.",
    "",
    "Free-form markdown headings (`## Notes`, `## Equipment`) and",
    "paragraphs work alongside the tags — the recipe is a document, not",
    "a fixed-shape form.",
    "",
    "Typical shape:",
    "",
    "```markdown",
    "---",
    "title: Pasta alla Norma",
    "source: Marcella Hazan",
    "tags: [pasta, sicilian]",
    "---",
    "{% yield amount=\"4\" %}4 servings{% /yield %}",
    "",
    "## Ingredients",
    "",
    "- {% ingredient amount=\"1\" unit=\"lb\" %}pasta{% /ingredient %}",
    "- {% ingredient amount=\"2\" unit=\"cups\" %}tomato sauce{% /ingredient %}",
    "",
    "## Steps",
    "",
    "{% step %}Boil the pasta.{% /step %}",
    "",
    "{% step %}Heat the sauce.{% /step %}",
    "```",
    "",
  ];
}
