/**
 * Marking provenance: where wrapped content came from and (optionally)
 * how it was derived. Renders as a small citation chip linking to the
 * source. Composes with `{% quote %}` for "verbatim from there."
 */

import { SECTION } from "./sections.js";

export function sourceSection(): string[] {
  return [
    `## ${SECTION.PROVENANCE} — the \`{% source %}\` tag`,
    "",
    "When you write content that's derived from another card or file —",
    "a summary of a memo, an inference from an email, a name pulled from",
    "a transcript — wrap it in a `{% source %}` tag so the origin stays",
    "visible. The complement to `{% quote %}`: where `{% quote %}` answers",
    "*whose exact words*, `{% source %}` answers *where the content came",
    "from*, optionally *how* it was derived.",
    "",
    "```",
    "{% source ref=\"/box/inbox/Voice_2026-03-15.memo.card\" usage=\"summary\" %}",
    "She's been going back and forth on the kitchen — open shelves vs.",
    "closed, mostly because she doesn't trust herself to keep them tidy.",
    "{% /source %}",
    "",
    "{% source ref=\"/box/people/Dana_Bicking.person.card\" usage=\"inferred from her email signature\" %}",
    "Dana lives in Portland.",
    "{% /source %}",
    "```",
    "",
    "### `ref` — pointing at another card",
    "",
    "`ref` is the box's pointer to another card, used throughout the guide:",
    "frontmatter (`{ref: \"...\"}`, `key-people[].ref`), body links, and tags",
    "like this one. A leading `/` resolves from the **box root** (the usual",
    "form); a bare path resolves relative to the current card; avoid `../../`.",
    "Refs are tracked automatically — `cb validate` warns when a `ref` no",
    "longer resolves, and `cb mv` rewrites them when the target moves. Inside",
    "`{% source %}`, exactly one of `ref` / `href` is **required** — it names",
    "where the wrapped content came from.",
    "",
    "### `usage` — how the source was used",
    "",
    "Optional, free-form natural language describing *the way the source material",
    "was used* to produce the wrapped content. Not an enum — write the truth.",
    "",
    "Examples spanning the range:",
    "",
    "- `usage=\"verbatim\"`",
    "- `usage=\"paraphrase\"`",
    "- `usage=\"summary of the third section\"`",
    "- `usage=\"calculated from the figures in the table\"`",
    "- `usage=\"inferred from Maria's preference for X\"`",
    "- `usage=\"extracted name\"`",
    "- `usage=\"agent's own framing based on the conversation\"`",
    "",
    "Honest description beats enum-fitting. If the derivation has a",
    "specific shape, name it. If it's just \"summarized,\" say so. Don't",
    "collapse everything into `verbatim` or `paraphrase` when the truth",
    "is sharper.",
    "",
    "### Composition with `{% quote %}`",
    "",
    "The two tags compose to express \"verbatim from there\":",
    "",
    "```",
    "{% source ref=\"/box/inbox/Voice_2026-03-15.memo.card\" usage=\"verbatim\" %}",
    "{% quote %}I keep going back and forth on the kitchen.{% /quote %}",
    "{% /source %}",
    "```",
    "",
    "Outer tag pins the origin; inner tag marks that the words are exact.",
    "Bare `{% source %}` without an inner `{% quote %}` is paraphrased /",
    "summarized / inferred content with a citation.",
    "",
    "### Anchoring an existing span (`pos`, `version`, `href`)",
    "",
    "When you're citing a *specific span of a specific version* of a file —",
    "as in a commentary card built from selections — `{% source %}` also",
    "carries:",
    "",
    "- `pos` — a rough locator. **Identical in form and meaning to the `pos` on",
    "  `<user-selection>` and `<card-activity>`** — same grammar (section, nearest",
    "  heading + `#id`, paragraph, approximate line), fully cross-referable. When",
    "  you carry a selection into an anchor, copy its `pos` verbatim.",
    "- `version` — space-separated `kind:value` markers pinning the file state",
    "  you anchored against: a `sha256:` content hash (the drift signal) and",
    "  optionally a `git:<rev>` (for later diffing). Measure these; don't invent.",
    "- `placement` — same field as on a `<user-selection>`: present when `pos` was",
    "  estimated, so a reader treats the spot as approximate. Copy it through too.",
    "- `href` instead of `ref` for an **external** target (a full URL: `file:`,",
    "  `http(s):`) — exactly one of `ref`/`href`, never both. `href` targets are",
    "  not tracked or rewritten by `cb mv`.",
    "",
    "### When to skip the tag",
    "",
    "Your own framing prose — connective tissue, transitions, your read",
    "of what something means — doesn't need a `{% source %}` tag. The tag",
    "marks the spans that *came from somewhere else*. The rest is yours.",
    "",
  ];
}
