/**
 * Marking provenance: where wrapped content came from and (optionally)
 * how it was derived. Renders as a small citation chip linking to the
 * source. Composes with `{% quote %}` for "verbatim from there."
 */

export function sourceSection(): string[] {
  return [
    "## Provenance — `{% source %}`",
    "",
    "When you write content that's derived from another card or file —",
    "a summary of a memo, an inference from an email, a name pulled from",
    "a transcript — wrap it in a `{% source %}` tag so the origin stays",
    "visible. The complement to `{% quote %}`: where `{% quote %}` answers",
    "*whose exact words*, `{% source %}` answers *where the content came",
    "from*, optionally *how* it was derived.",
    "",
    "```",
    "{% source ref=\"/box/inbox/Voice_2026-03-15.memo.card\" as=\"summary\" %}",
    "She's been going back and forth on the kitchen — open shelves vs.",
    "closed, mostly because she doesn't trust herself to keep them tidy.",
    "{% /source %}",
    "",
    "{% source ref=\"/box/people/dana.person.card\" as=\"inferred from her email signature\" %}",
    "Dana lives in Portland.",
    "{% /source %}",
    "```",
    "",
    "### The `ref` attribute",
    "",
    "Required. Where the content came from — a card path, a file, or a",
    "card path plus a fragment (`#m12` for a chat message, `#step-3` for",
    "a procedure step). Leading `/` is box-root-absolute (the usual form);",
    "bare paths resolve relative to the source card. Body refs are tracked",
    "automatically — `cb validate` warns when a `ref` no longer resolves,",
    "and `cb mv` rewrites them when the target moves.",
    "",
    "### The `as` attribute",
    "",
    "Optional, free-form natural language describing *how* the wrapped",
    "content derives from the source. Not an enum — write the truth.",
    "",
    "Examples spanning the range:",
    "",
    "- `as=\"verbatim\"`",
    "- `as=\"paraphrase\"`",
    "- `as=\"summary of the third section\"`",
    "- `as=\"calculated from the figures in the table\"`",
    "- `as=\"inferred from Maria's preference for X\"`",
    "- `as=\"extracted name\"`",
    "- `as=\"agent's own framing based on the conversation\"`",
    "",
    "Honest description beats enum-fitting. If the derivation has a",
    "specific shape, name it. If it's just \"summarized,\" say so. Don't",
    "collapse everything into `verbatim` or `paraphrase` when the truth",
    "is sharper.",
    "",
    "### Composition with `{% quote %}`",
    "",
    "The two tags compose to express \"verbatim from there\":",
    "",
    "```",
    "{% source ref=\"/box/inbox/Voice_2026-03-15.memo.card\" as=\"verbatim\" %}",
    "{% quote %}I keep going back and forth on the kitchen.{% /quote %}",
    "{% /source %}",
    "```",
    "",
    "Outer tag pins the origin; inner tag marks that the words are exact.",
    "Bare `{% source %}` without an inner `{% quote %}` is paraphrased /",
    "summarized / inferred content with a citation.",
    "",
    "### Anchoring an existing span (`pos`, `version`, `href`)",
    "",
    "When you're citing a *specific span of a specific version* of a file —",
    "as in a commentary card built from selections — `{% source %}` also",
    "carries:",
    "",
    "- `pos` — a rough locator (section, nearest heading + `#id`, paragraph,",
    "  approximate line), the same shape a chat `<user-selection>` carries.",
    "- `version` — space-separated `kind:value` markers pinning the file state",
    "  you anchored against: a `sha256:` content hash (the drift signal) and",
    "  optionally a `git:<rev>` (for later diffing). Measure these; don't invent.",
    "- `placement` — present (carried from a `<user-selection>`) when `pos` was",
    "  estimated, so a reader treats the spot as approximate.",
    "- `href` instead of `ref` for an **external** target (a full URL: `file:`,",
    "  `http(s):`) — exactly one of `ref`/`href`, never both. `href` targets are",
    "  not tracked or rewritten by `cb mv`.",
    "",
    "### When to skip the tag",
    "",
    "Your own framing prose — connective tissue, transitions, your read",
    "of what something means — doesn't need a `{% source %}` tag. The tag",
    "marks the spans that *came from somewhere else*. The rest is yours.",
    "",
  ];
}
