/**
 * Bookmark card schema - Raindrop.io bookmarks.
 *
 * Two-way synced via the Raindrop connector.
 * Cards live in box/bookmarks/ with collection as a flat attribute.
 */

import { element, serialize } from "cardworks";
import { z } from "zod";

/**
 * Child element for a single tag.
 */
export const BookmarkTag = element("tag", {
  text: z.string(),
});

/**
 * Container for tags.
 */
export const BookmarkTags = element("tags", {
  children: z.array(BookmarkTag).optional(),
});

/**
 * Child element for the bookmark title.
 */
export const BookmarkTitle = element("title", {
  text: z.string(),
});

/**
 * Child element for the bookmark URL.
 */
export const BookmarkLink = element("link", {
  text: z.string().url(),
});

/**
 * Child element for Raindrop's auto-generated excerpt.
 */
export const BookmarkExcerpt = element("excerpt", {
  text: z.string(),
});

/**
 * Child element for user-written notes.
 */
export const BookmarkNote = element("note", {
  text: z.string(),
});

/**
 * Child element for creation timestamp.
 */
export const BookmarkCreated = element("created", {
  text: z.string().datetime({ offset: true }),
});

/**
 * Child element for last-updated timestamp.
 */
export const BookmarkUpdated = element("updated", {
  text: z.string().datetime({ offset: true }),
});

/**
 * Bookmark card schema.
 *
 * Example:
 * ```xml
 * <bookmark raindrop-id="12345678" collection="Dev Resources">
 *   <title>How to Build a CLI in TypeScript</title>
 *   <link>https://example.com/article</link>
 *   <excerpt>A guide to building modern CLI tools</excerpt>
 *   <note>Useful for the callback-box project</note>
 *   <tags>
 *     <tag>typescript</tag>
 *     <tag>cli</tag>
 *   </tags>
 *   <created>2024-01-15T10:00:00Z</created>
 *   <updated>2024-01-16T12:00:00Z</updated>
 * </bookmark>
 * ```
 */
export const BookmarkSchema = element("bookmark", {
  attrs: {
    /** Raindrop bookmark ID. Absent means "create on next push". */
    "raindrop-id": z.string().optional(),
    /** Collection name. Default: "Unsorted". */
    collection: z.string().optional(),
  },
  children: z.array(
    z.union([
      BookmarkTitle,
      BookmarkLink,
      BookmarkExcerpt,
      BookmarkNote,
      BookmarkTags,
      BookmarkCreated,
      BookmarkUpdated,
    ])
  ),
  instructions: `# Handling Bookmarks

Bookmarks are two-way synced with Raindrop.io via \`cb wakeup\`.

- **raindrop-id**: Links to the Raindrop bookmark. Leave absent to create a new bookmark on next sync.
- **collection**: Raindrop collection name (flat string). Defaults to "Unsorted".
- **title**, **link**: The bookmark's title and URL. Editable — changes push to Raindrop.
- **note**: User-written notes. Editable — changes push to Raindrop.
- **tags**: Editable — changes push to Raindrop.
- **excerpt**: Auto-generated by Raindrop. Informational only, not pushed.
- **created**, **updated**: Timestamps from Raindrop. Informational only.

To add a new bookmark locally, create a card with at least a <link> element (and optionally title, tags, note, collection). On next \`cb wakeup\`, it will be created in Raindrop and receive a raindrop-id.`,
});

export type Bookmark = z.infer<typeof BookmarkSchema>;

/**
 * Template for creating a bookmark card.
 */
export function createBookmarkTemplate(options: {
  title: string;
  link: string;
  raindropId?: string;
  collection?: string;
  excerpt?: string;
  note?: string;
  tags?: string[];
  created?: string;
  updated?: string;
}): string {
  const bookmark = (
    <bookmark
      raindrop-id={options.raindropId}
      collection={options.collection || "Unsorted"}
    >
      <title>{options.title}</title>
      <link>{options.link}</link>
      {options.excerpt && <excerpt>{options.excerpt}</excerpt>}
      {options.note && <note>{options.note}</note>}
      {options.tags && options.tags.length > 0 && (
        <tags>
          {options.tags.map((t) => (
            <tag>{t}</tag>
          ))}
        </tags>
      )}
      {options.created && <created>{options.created}</created>}
      {options.updated && <updated>{options.updated}</updated>}
    </bookmark>
  );

  return serialize(bookmark) + "\n";
}
