/**
 * Capture session card schema (Phase-2 frontmatter + Markdoc transcript body).
 *
 * Created by the capture connector. Frontmatter carries the session
 * metadata and the manifests of child image/audio/file cards (which live
 * in the session's attach scope). The markdown body is the assembled
 * transcript: transcribed speech interleaved, in timeline order, with
 * `{% image %}` markers (where a photo was taken) and `{% silence %}`
 * markers (gaps) — see `src/shared/markdoc-config.ts`.
 *
 * Later procedures transcribe audio, analyze images, and assemble the
 * transcript (`assemble-timeline`).
 */

import { parse as parseYaml, stringify as stringifyYaml } from "yaml";
import { z } from "zod";
import { splitCardContent, body, cardSchema, type CardSchema } from "../cards/index.js";

export const CaptureSessionStatus = z.enum([
  "new",
  "transcribing",
  "transcribed",
  "intake-complete",
  "extracted",
]);
export type CaptureSessionStatus = z.infer<typeof CaptureSessionStatus>;

const SessionTime = z.object({
  start: z.string().datetime({ offset: true }),
  end: z.string().datetime({ offset: true }).optional(),
  duration: z.string().optional(),
});

const captureSessionFields = {
  status: CaptureSessionStatus.default("new"),
  "session-id": z.string(),
  time: SessionTime.optional(),
  /** Manifest of child image cards (refs into the session's attach scope). */
  images: z.array(z.string()).optional(),
  /** Manifest of child audio cards. */
  "audio-clips": z.array(z.string()).optional(),
  /** Manifest of child uploaded-file cards. */
  files: z.array(z.string()).optional(),
  /** The assembled transcript (markdown + `{% image %}` / `{% silence %}`). */
  body: body(z.string()),
};

export const CaptureSessionSchema: CardSchema = cardSchema("capture-session", {
  description: "Groups the images, audio clips, and files from one recording session, with an assembled timeline transcript as the body",
  category: "synced",
  searchable: true,
  fields: captureSessionFields,
  instructions: `# Capture Session Cards

A capture session groups images, audio clips, and uploaded files from a single recording session (e.g., a voice walkthrough with photos, or a batch of documents). The session card lives at the inbox level; its child cards (audio, image, file) live inside the session's attach scope (\`{basename}.attach/\`). Refs to children use the \`attach/\` virtual prefix.

Frontmatter:
- \`status\` — new → transcribing → transcribed (audio done) → intake-complete (images described, timeline assembled) → extracted (records pulled into a catalog directory).
- \`session-id\` — links back to the capture API.
- \`time\` — \`{ start, end?, duration? }\`.
- \`images\` / \`audio-clips\` / \`files\` — manifests of the child card refs.

Body — the assembled transcript, a timeline of transcribed speech interleaved with:
- \`{% image ref="photo-001.image.card" /%}\` — where a photo was taken (description/filename come from the referenced image card).
- \`{% silence duration="15s" /%}\` — gaps of 10+ seconds.

The transcript is generated by \`assemble-timeline\`; agents read it to extract records but shouldn't usually hand-edit it.`,
});

/** Frontmatter-only object schema (the body field lives outside Zod). */
const CaptureSessionObject = z.object({
  status: CaptureSessionStatus.default("new"),
  "session-id": z.string(),
  time: SessionTime.optional(),
  images: z.array(z.string()).optional(),
  "audio-clips": z.array(z.string()).optional(),
  files: z.array(z.string()).optional(),
});
export type CaptureSessionFrontmatter = z.infer<typeof CaptureSessionObject>;
/** Back-compat alias. */
export type CaptureSession = CaptureSessionFrontmatter;

/**
 * A capture session's parsed frontmatter plus its raw transcript body, or
 * null if the text has no frontmatter / fails validation. Used by the
 * timeline assembler and other readers that work with the card directly.
 */
export interface ParsedCaptureSession {
  frontmatter: CaptureSessionFrontmatter;
  body: string;
}

export function parseCaptureSession(content: string): ParsedCaptureSession | null {
  const split = splitCardContent(content);
  if (!split.hasFrontmatter) return null;
  let fm: unknown;
  try {
    fm = parseYaml(split.frontmatterText);
  } catch (_e) {
    return null;
  }
  const parsed = CaptureSessionObject.safeParse(fm ?? {});
  if (!parsed.success) return null;
  return { frontmatter: parsed.data, body: split.body };
}

/**
 * Template for creating a capture session card — frontmatter manifests with
 * an empty transcript body (filled in later by `assemble-timeline`).
 *
 * `imageRefs`, `audioRefs`, `fileRefs` are bare child-card filenames
 * (e.g. `photo-001.image.card`). They're emitted with the `attach/` virtual
 * prefix, pointing into the session's attach scope.
 */
export function createCaptureSessionTemplate(options: {
  sessionId: string;
  startedAt: string;
  endedAt?: string | null;
  imageRefs: string[];
  audioRefs: string[];
  fileRefs?: string[];
}): string {
  const duration = options.endedAt
    ? formatDuration(new Date(options.endedAt).getTime() - new Date(options.startedAt).getTime())
    : undefined;

  const time: Record<string, string> = { start: options.startedAt };
  if (options.endedAt) time.end = options.endedAt;
  if (duration !== undefined) time.duration = duration;

  const fields: Record<string, unknown> = {
    status: "new",
    "session-id": options.sessionId,
    time,
    images: options.imageRefs.map((ref) => `attach/${ref}`),
    "audio-clips": options.audioRefs.map((ref) => `attach/${ref}`),
  };
  const fileRefs = options.fileRefs ?? [];
  if (fileRefs.length > 0) fields.files = fileRefs.map((ref) => `attach/${ref}`);

  return `---\n${stringifyYaml(fields)}---\n`;
}

/**
 * Format a duration in milliseconds to a human-readable string like "4m2s" or "1h15m".
 */
function formatDuration(ms: number): string {
  const totalSeconds = Math.floor(ms / 1000);
  const hours = Math.floor(totalSeconds / 3600);
  const minutes = Math.floor((totalSeconds % 3600) / 60);
  const seconds = totalSeconds % 60;
  if (hours > 0) {
    return minutes > 0 ? `${hours}h${minutes}m` : `${hours}h`;
  }
  if (minutes > 0) {
    return seconds > 0 ? `${minutes}m${seconds}s` : `${minutes}m`;
  }
  return `${seconds}s`;
}
