/**
 * Scheduling/automation + chat command sections for the `cb` command
 * reference doc. Split out of generate-docs-cb-commands.ts to keep each
 * file under the line limit; assembled there by generateCbCommands().
 */

/**
 * Hand-written command sections: procedure, tick, scheduled, scheduler, finalize,
 * scenario.
 */
export function cbCommandsScheduling(): string[] {
  return [
    "## cb procedure",
    "",
    "Run and manage declarative procedures. See `docs/generated/procedures.md` for details.",
    "",
    "```bash",
    "cb procedure run <name-or-path>          # Run a procedure",
    "cb procedure run <name> --step <id>      # Run a single step",
    "cb procedure run <name> --dry-run        # Preview without executing",
    'cb procedure run <name> --directive "text" # Pass a directive to agents',
    "cb procedure list                        # List available procedures",
    "cb procedure status [run-dir]            # Show status of latest/specific run",
    "```",
    "",
    "The `<name-or-path>` argument can be a bare name (resolves to `config/procedures/<name>.procedure.card`)",
    "or a direct path to any `.procedure.card` file.",
    "",
    "The `--directive` flag passes an opaque string that appears as `<directive>...</directive>` in every agent's",
    "system prompt within the procedure. Use it to customize behavior without modifying the procedure card.",
    "",
    "## cb tick",
    "",
    "Evaluate scheduled scripts and run any that are due.",
    "",
    "```",
    "cb tick [--dry-run] [--script <name>] [--force] [--box <path>]",
    "```",
    "",
    "Checks all `config/schedules/*.scheduled-script.card` files against their cron/at/rrule schedules.",
    "Runs due scripts, updates last-run timestamps, and deletes one-shot (`once`) scripts after execution.",
    "",
    "**Options:**",
    "- `--dry-run` — Show which scripts would run without executing them",
    "- `--script <name>` — Only evaluate a specific script (by filename stem)",
    "- `--force` — Run the `--script` now, bypassing schedule, budget, and active-chat checks. Use this when the boxholder asks for a run from chat — a plain tick defers on the chat session itself. Running scripts/procedures and live lock-group holders still defer; force never preempts running work.",
    "- `--box <path>` — Target a specific box instead of the current directory",
    "",
    "Note: scripts with `on-wakeup=\"true\"` also run during `cb wakeup`, subject to their `not-before` interval.",
    "",
    "## cb scheduled",
    "",
    "List all scheduled scripts and their status.",
    "",
    "```",
    "cb scheduled",
    "```",
    "",
    "Shows each schedule's name, type (cron/at/rrule), next due time, last run, and flags (on-wakeup, once, enabled).",
    "",
    "## cb health",
    "",
    "Show scheduled-task health: failing, overdue, blocked, or invalid tasks, plus",
    "whether the scheduler daemon is alive.",
    "",
    "```",
    "cb health [--json] [--all] [--box <path>]",
    "```",
    "",
    "Per task: status, last attempt vs last success (they diverge while failing),",
    "consecutive-failure count, and the last error. `--all` includes disabled tasks.",
    "Exit code 1 when anything is failing/overdue/invalid or the scheduler heartbeat",
    "is stale, so scripts can gate on it. Deliberate skips (budget exhausted, missing",
    "connector, disabled) show as blocked/disabled, never as failures.",
    "",
    "## cb scheduler",
    "",
    "Manage the background scheduler daemon that runs `cb tick` on a recurring basis.",
    "",
    "```",
    "cb scheduler start [--interval <seconds>]  # Run daemon (foreground)",
    "cb scheduler add <path>                    # Add box to scheduler",
    "cb scheduler remove <path>                 # Remove box",
    "cb scheduler list                          # Show configured boxes",
    "cb scheduler status                        # Show boxes + launchd status",
    "cb scheduler log [--box <path>] [--limit <n>] [--errors] [--json]",
    "cb scheduler install                       # Install launchd plist",
    "cb scheduler uninstall                     # Remove launchd plist",
    "```",
    "",
    "The daemon polls every 60 seconds (configurable). Config at `~/.config/cb/scheduler.json`.",
    "Per-box logs are written to `.callback-box/scheduler.jsonl` (JSONL, auto-rotated at 1MB).",
    "Each log entry records which scripts ran/skipped/errored with timestamps and durations.",
    "Agents can read `.callback-box/scheduler.jsonl` to understand recent scheduling activity.",
    "",
    "## cb finalize",
    "",
    "Run outbound connectors to flush pending output cards.",
    "",
    "```",
    "cb finalize [-c, --connector <name>]",
    "```",
    "",
    "Symmetric counterpart to `cb wakeup`. Sends any pending cards in `box/output/`",
    "(e.g. telegram messages). Called automatically by the reactor after job processing,",
    "or run manually to flush output.",
    "",
    "## cb scenario",
    "",
    "Run scenario tests against boxes. Scenarios live in `~/src/boxes/scenarios/`.",
    "",
    "```bash",
    "cb scenario list                          # List available scenarios",
    "cb scenario run <name>                    # Run a scenario",
    "cb scenario run <name> --dry-run          # Preview steps",
    "```",
    "",
    ...cbCommandsChat(),
  ];
}

/** The `## cb chat` section: self-note + the voice-recording commands. */
function cbCommandsChat(): string[] {
  return [
    "## cb chat",
    "",
    "Talk to the live chat session.",
    "",
    "- `cb chat self-note \"<body>\" [--ref <path>] [--commit <hash>]` — Post an",
    "  agent-authored record into the chat transcript without triggering a reply.",
    "- `cb chat screenshot [--session <id>] [--timeout <seconds>]` — Ask the",
    "  user's connected chat tab for a screenshot of what they currently see in",
    "  the box UI, and print the saved image path (Read it) plus a `fidelity:`",
    "  line. Reach for it on visual/layout questions — how a card or custom view",
    "  actually renders — where `whats-changed` (content) and reading the source",
    "  can't help. It asks the user's browser, so instead of a path it may print",
    "  one of `declined:` / `no-client:` / `timeout:` / `failed:` / `error:`",
    "  telling you it was declined or unavailable. Defaults: the session from",
    "  `CB_CHAT_SESSION_ID`, a 45s wait.",
    "- `cb chat ask-about-audio \"<question>\" --message <id> [--context <text>]`",
    "  — Ask an audio-capable model (Gemini) a question about a specific voice",
    "  message (or `--file <path>` for any audio file). `--message` is",
    "  required unless `--file` is given: read the `message-id=\"…\"` attribute",
    "  off the `<speech>` wrapper of the message you mean — never fabricate",
    "  it. Claude can't listen to audio itself; use this when the exact audio",
    "  matters — a mangled-but-important transcription, pronunciation, tone —",
    "  not routine chat. The system's own transcript rides along automatically",
    "  so the model can flag transcription flaws; `--context` supplies",
    "  conversational background (what the message responds to), and",
    "  `--transcript` overrides the known transcription.",
    "- `cb chat retranscribe --message <id> [--diarize] [--service <name>]` —",
    "  Re-run a specific voice message (same `--message` targeting, or",
    "  `--file <path>`) through the high-quality transcription pass",
    "  (Whisper/Voxtral; default is the box's `hqService` config). For when",
    "  the realtime transcript looks wrong and you just need the correct",
    "  text — cheaper and more direct than `ask-about-audio`. Skip it when",
    "  the message's wrapper already says `stt=\"hq\"` — that text came from",
    "  the better model already, so retranscribing has nothing to add.",
    "  `--diarize` labels speakers. Prints the HQ transcript plus a `realtime-transcript:`",
    "  line for comparison. A successful run shows the corrected text on the",
    "  user's message automatically — don't paste it back unless asked.",
    "- `cb chat get-last-audio --message <id> [--out <path>]` — Fetch the raw",
    "  recording of a specific voice message to a temp file; prints the path.",
    "  Use when you need the file itself rather than an answer about it.",
    "",
    "A bare command (no `--message`) errors — these commands never guess",
    "which recording you mean. The recording is available only while the chat",
    "tab that recorded it is open, and only for the last few voice messages",
    "(the retention window).",
    "",
  ];
}
